slogo_team17: model.IVariablesCollection Interface Reference
model.IVariablesCollection Interface Reference
Public Member Functions
abstract Object getVariableValue (String varName)
abstract void addVariable (String varName, String varValue) throws VariableCreationException, VariableCreationInvalidValueException
void addObserver (Observer o)
void removeObserver (Observer o)
void notifyObservers ()
String saveState ()
void enterScope ()
void exitScope ()
Detailed Description
Definition at line 8 of file IVariablesCollection.java.
Member Function Documentation
void model.IVariablesCollection.addObserver (Observer o)
Implements model.Observable.
Implemented in model.VariablesCollection, and model.ScopedVariablesCollection.
Referenced by model.State.State().
abstract void model.IVariablesCollection.addVariable (String varName, String varValue) throws VariableCreationException, VariableCreationInvalidValueException abstract
Implemented in model.VariablesCollection, and model.ScopedVariablesCollection.
void model.IVariablesCollection.enterScope ()
Implemented in model.VariablesCollection, and model.ScopedVariablesCollection.
Referenced by parser.commands.ToInstance.execute().
void model.IVariablesCollection.exitScope ()
Implemented in model.VariablesCollection, and model.ScopedVariablesCollection.
Referenced by parser.commands.ToInstance.execute().
abstract Object model.IVariablesCollection.getVariableValue (String varName) abstract
Implemented in model.ScopedVariablesCollection, and model.VariablesCollection.
void model.IVariablesCollection.notifyObservers ()
Implements model.Observable.
Implemented in model.VariablesCollection, and model.ScopedVariablesCollection.
void model.IVariablesCollection.removeObserver (Observer o)
Implements model.Observable.
Implemented in model.VariablesCollection, and model.ScopedVariablesCollection.
String model.IVariablesCollection.saveState ()
Concatenates a String that contains all the necessary variable declarations to recreate the variable collection, for the purpose of saving.
Implemented in model.VariablesCollection, and model.ScopedVariablesCollection.
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/IVariablesCollection.java