slogo_team17: view.components.TurtleWindow Class Reference
view.components.TurtleWindow Class Reference
Public Member Functions
TurtleWindow (double width, double height)
void addTurtle ()
void addTurtle (int id)
void updateAnimationSpeed (double speed)
void changeBackground (Color c)
Color getBackgroundColor ()
void changePenColor (Color c, int turtleID)
void changeTurtleImage (File file, int turtleID)
List< Integer > getAvailableTurtles ()
int getNumOfTurtles ()
void toggleInactiveTurtles (boolean show)
void enterDebugMode ()
void exitDebugMode ()
void stepDebug ()
void update (Object update)
Private Member Functions
void initializeMenu ()
void popMyMenu (MouseEvent event)
void setDefaultImagePalette ()
void setDefaultColorPalette ()
void setImagePaletteMenu ()
void setColorPaletteMenu ()
void modifyImagePaletteMenu (int index)
void modifyColorPaletteMenu (int index)
Private Attributes
Canvas mainCanvas
GraphicsContext mainGC
double myWidth
double myHeight
IntegerProperty bgColorID
Integer initialColorIndex = 1
int numTurtles
int activeTurtleID
boolean showInactiveTurtles
Group myLayers = new Group()
HashMap< Integer, GraphicsContext > gc = new HashMap<>()
HashMap< Integer, TurtleImage > myTurtles = new HashMap<>()
Palette myPalette = new Palette()
Group myTImages = new Group()
ContextMenu contextMenu
Menu imagePalettes
Menu colorPalettes
ToggleGroup imagePaletteGroup = new ToggleGroup()
ToggleGroup colorPaletteGroup = new ToggleGroup()
Detailed Description
Definition at line 33 of file TurtleWindow.java.
Constructor & Destructor Documentation
view.components.TurtleWindow.TurtleWindow (double width, double height)
Definition at line 59 of file TurtleWindow.java.
References view.components.TurtleWindow.addTurtle(), view.components.TurtleWindow.changeBackground(), and view.components.TurtleWindow.initializeMenu().
Member Function Documentation
void view.components.TurtleWindow.addTurtle ()
Definition at line 184 of file TurtleWindow.java.
Referenced by view.toolbar.AddTurtleToolbarItem.createNode(), and view.components.TurtleWindow.TurtleWindow().
void view.components.TurtleWindow.addTurtle (int id)
Definition at line 195 of file TurtleWindow.java.
void view.components.TurtleWindow.changeBackground (Color c)
Definition at line 222 of file TurtleWindow.java.
Referenced by view.toolbar.BackgroundColorToolbarItem.createNode(), view.components.SLogoMenuBar.makePreferencesMenu(), and view.components.TurtleWindow.TurtleWindow().
void view.components.TurtleWindow.changePenColor (Color c, int turtleID)
Definition at line 232 of file TurtleWindow.java.
Referenced by view.toolbar.TurtlePenColorToolbarItem.changeTurtleProperties().
void view.components.TurtleWindow.changeTurtleImage (File file, int turtleID)
Definition at line 237 of file TurtleWindow.java.
Referenced by view.toolbar.TurtleImageToolbarItem.changeTurtleProperties().
void view.components.TurtleWindow.enterDebugMode ()
Definition at line 264 of file TurtleWindow.java.
References view.turtle.TurtleImage.setDebugMode().
Referenced by view.components.SLogoWorkspace.startDebugger().
void view.components.TurtleWindow.exitDebugMode ()
Definition at line 270 of file TurtleWindow.java.
References view.turtle.TurtleImage.setRunMode().
Referenced by view.components.SLogoWorkspace.stopDebugger().
List<Integer> view.components.TurtleWindow.getAvailableTurtles ()
Definition at line 242 of file TurtleWindow.java.
Referenced by view.toolbar.TurtleSpecificToolbarItem.getAvailableTurtles(), and view.toolbar.TurtleSpecificToolbarItem.getUserInput().
Color view.components.TurtleWindow.getBackgroundColor ()
Definition at line 227 of file TurtleWindow.java.
int view.components.TurtleWindow.getNumOfTurtles ()
Definition at line 248 of file TurtleWindow.java.
void view.components.TurtleWindow.initializeMenu () private
Definition at line 82 of file TurtleWindow.java.
References view.components.TurtleWindow.popMyMenu(), view.components.TurtleWindow.setColorPaletteMenu(), view.components.TurtleWindow.setDefaultColorPalette(), view.components.TurtleWindow.setDefaultImagePalette(), and view.components.TurtleWindow.setImagePaletteMenu().
Referenced by view.components.TurtleWindow.TurtleWindow().
void view.components.TurtleWindow.modifyColorPaletteMenu (int index) private
Definition at line 175 of file TurtleWindow.java.
References view.dialogs.InputDialogBox.showInputDialog().
void view.components.TurtleWindow.modifyImagePaletteMenu (int index) private
Definition at line 160 of file TurtleWindow.java.
References view.dialogs.InputDialogBox.showInputDialog().
void view.components.TurtleWindow.popMyMenu (MouseEvent event) private
Definition at line 99 of file TurtleWindow.java.
Referenced by view.components.TurtleWindow.initializeMenu().
void view.components.TurtleWindow.setColorPaletteMenu () private
Definition at line 140 of file TurtleWindow.java.
Referenced by view.components.TurtleWindow.initializeMenu().
void view.components.TurtleWindow.setDefaultColorPalette () private
Definition at line 113 of file TurtleWindow.java.
Referenced by view.components.TurtleWindow.initializeMenu().
void view.components.TurtleWindow.setDefaultImagePalette () private
Definition at line 106 of file TurtleWindow.java.
Referenced by view.components.TurtleWindow.initializeMenu().
void view.components.TurtleWindow.setImagePaletteMenu () private
Definition at line 120 of file TurtleWindow.java.
Referenced by view.components.TurtleWindow.initializeMenu().
void view.components.TurtleWindow.stepDebug ()
Definition at line 275 of file TurtleWindow.java.
References view.turtle.TurtleImage.popUpdate().
Referenced by view.components.SLogoWorkspace.runDebugger().
void view.components.TurtleWindow.toggleInactiveTurtles (boolean show)
Definition at line 253 of file TurtleWindow.java.
Referenced by view.toolbar.ShowTurtlesToolbarItem.createNode().
void view.components.TurtleWindow.update (Object update)
Implements view.components.Observer.
Definition at line 283 of file TurtleWindow.java.
References model.ViewInitializer.getBackgroundID(), model.ViewUpdate.getPaletteB(), model.ViewUpdate.getPaletteG(), model.ViewUpdate.getPaletteIndex(), model.ViewUpdate.getPaletteR(), model.PenUpdate.getTurtleID(), model.TurtleUpdate.getTurtleID(), model.ViewUpdate.isClearStamps(), and view.turtle.TurtleImage.updatePalette().
void view.components.TurtleWindow.updateAnimationSpeed (double speed)
Definition at line 215 of file TurtleWindow.java.
Referenced by view.toolbar.Toolbar.Toolbar().
Member Data Documentation
int view.components.TurtleWindow.activeTurtleID private
Definition at line 43 of file TurtleWindow.java.
IntegerProperty view.components.TurtleWindow.bgColorID private
Definition at line 39 of file TurtleWindow.java.
ToggleGroup view.components.TurtleWindow.colorPaletteGroup = new ToggleGroup() private
Definition at line 57 of file TurtleWindow.java.
Menu view.components.TurtleWindow.colorPalettes private
Definition at line 55 of file TurtleWindow.java.
ContextMenu view.components.TurtleWindow.contextMenu private
Definition at line 53 of file TurtleWindow.java.
HashMap<Integer, GraphicsContext> view.components.TurtleWindow.gc = new HashMap<>() private
Definition at line 48 of file TurtleWindow.java.
ToggleGroup view.components.TurtleWindow.imagePaletteGroup = new ToggleGroup() private
Definition at line 56 of file TurtleWindow.java.
Menu view.components.TurtleWindow.imagePalettes private
Definition at line 54 of file TurtleWindow.java.
Integer view.components.TurtleWindow.initialColorIndex = 1 private
Definition at line 40 of file TurtleWindow.java.
Canvas view.components.TurtleWindow.mainCanvas private
Definition at line 35 of file TurtleWindow.java.
GraphicsContext view.components.TurtleWindow.mainGC private
Definition at line 36 of file TurtleWindow.java.
double view.components.TurtleWindow.myHeight private
Definition at line 38 of file TurtleWindow.java.
Group view.components.TurtleWindow.myLayers = new Group() private
Definition at line 47 of file TurtleWindow.java.
Palette view.components.TurtleWindow.myPalette = new Palette() private
Definition at line 50 of file TurtleWindow.java.
Group view.components.TurtleWindow.myTImages = new Group() private
Definition at line 51 of file TurtleWindow.java.
HashMap<Integer, TurtleImage> view.components.TurtleWindow.myTurtles = new HashMap<>() private
Definition at line 49 of file TurtleWindow.java.
double view.components.TurtleWindow.myWidth private
Definition at line 37 of file TurtleWindow.java.
int view.components.TurtleWindow.numTurtles private
Definition at line 42 of file TurtleWindow.java.
boolean view.components.TurtleWindow.showInactiveTurtles private
Definition at line 45 of file TurtleWindow.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/components/TurtleWindow.java