slogo_team17: model.State Class Reference
model.State Class Reference
Public Member Functions
State ()
TurtleMultiple getTurtle ()
IVariablesCollection getVariablesCollection ()
CommandHistory getCommandHistory ()
ViewOptions getViewOptions ()
Private Attributes
TurtleMultiple myTurtleMultiple
IVariablesCollection myVariablesCollection
CommandHistory myCommandHistory
ViewOptions myViewOptions
Detailed Description
Class that contains all the information that can change due to user actions.
Definition at line 12 of file State.java.
Constructor & Destructor Documentation
model.State.State ()
Definition at line 18 of file State.java.
References model.IVariablesCollection.addObserver(), model.ViewOptions.addObserver(), model.CommandHistory.addObserver(), view.View.getCommandHistoryWindow(), view.View.getInstance(), view.View.getTurtleWindow(), view.View.getUDCommandsWindow(), view.View.getVariablesWindow(), and model.ViewOptions.initialize().
Member Function Documentation
CommandHistory model.State.getCommandHistory ()
Definition at line 36 of file State.java.
References model.State.myCommandHistory.
Referenced by parser.commands.ToData.execute(), and model.Model.parse().
TurtleMultiple model.State.getTurtle ()
Definition at line 30 of file State.java.
References model.State.myTurtleMultiple.
Referenced by parser.commands.PenDown.execute(), parser.commands.PenUp.execute(), and parser.commands.ParserTest.testParse().
IVariablesCollection model.State.getVariablesCollection ()
Definition at line 33 of file State.java.
References model.State.myVariablesCollection.
ViewOptions model.State.getViewOptions ()
Definition at line 39 of file State.java.
References model.State.myViewOptions.
Member Data Documentation
CommandHistory model.State.myCommandHistory private
Definition at line 15 of file State.java.
Referenced by model.State.getCommandHistory().
TurtleMultiple model.State.myTurtleMultiple private
Definition at line 13 of file State.java.
Referenced by model.State.getTurtle().
IVariablesCollection model.State.myVariablesCollection private
Definition at line 14 of file State.java.
Referenced by model.State.getVariablesCollection().
ViewOptions model.State.myViewOptions private
Definition at line 16 of file State.java.
Referenced by model.State.getViewOptions().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/State.java