slogo_team17: view.turtle.TurtleImage Class Reference
view.turtle.TurtleImage Class Reference
Public Member Functions
TurtleImage (GraphicsContext gcon, int id)
TurtleImage (GraphicsContext gcon, int id, String imagePath, double xPos, double yPos, double width, double height)
void hide (boolean hidden)
void changeImage (Image img)
void changeImage (String imagePath)
void changeImage (File file)
void resize (double width, double height)
void setDebugMode ()
void setRunMode ()
void setPenProperties (PenUpdate pu)
void updatePalette (Palette p)
void addUpdate (TurtleUpdate tu)
void popUpdate ()
void processUpdate (TurtleUpdate tu)
void setAnimationSpeed (double speed)
void clearStamps ()
Node getStamps ()
Private Member Functions
void animatedMove (double toAngle, Point2D toLocation)
void unanimatedMove (double toAngle, Point2D toLocation)
void initializeMenu ()
void popMyMenu ()
MenuItem makeMenuItem (String label, EventHandler< ActionEvent > event)
Transition createRotateTransition (double destination)
Transition createTranslateTransition (Point2D destination)
void installStateTooltip ()
void selectPenColor ()
void selectImageFile ()
void toggleTurtle ()
void setPenUpDown ()
void setLineStyleMenu ()
void setLineWidthMenu ()
Point2D mathCoordsToCanvasCoords (Point2D mathCoords)
Point2D canvasCoordsToMathCoords (Point2D canvasCoords)
void leaveStamp ()
Private Attributes
Image myImage
GraphicsContext gc
TurtlePen myPen
int myID
double myWidth
double myHeight
double mySpeed
boolean busy
boolean debugMode
PriorityQueue< TurtleUpdate > pendingUpdates
Palette myPalette
Boolean active
Boolean visible
Boolean penUp
Group myStamps
ContextMenu contextMenu
MenuItem changeImage
MenuItem toggle
MenuItem penColor
Menu lineStyle
Menu lineWidth
MenuItem penUpDown
Static Private Attributes
static final double DEFAULT_XPOS = 0
static final double DEFAULT_YPOS = 0
static final String DEFAULT_IMAGEPATH = "/resources/images/turtle-top-view.png"
static final double DEFAULT_WIDTH = 30
static final double DEFAULT_HEIGHT = 30
static final double DEFAULT_SPEED = 0.6
static final double ANIMATION_THRESHOLD = 1.5
Detailed Description
Definition at line 36 of file TurtleImage.java.
Constructor & Destructor Documentation
view.turtle.TurtleImage.TurtleImage (GraphicsContext gcon, int id)
Definition at line 75 of file TurtleImage.java.
References view.turtle.TurtleImage.DEFAULT_HEIGHT, view.turtle.TurtleImage.DEFAULT_IMAGEPATH, view.turtle.TurtleImage.DEFAULT_WIDTH, view.turtle.TurtleImage.DEFAULT_XPOS, and view.turtle.TurtleImage.DEFAULT_YPOS.
view.turtle.TurtleImage.TurtleImage (GraphicsContext gcon, int id, String imagePath, double xPos, double yPos, double width, double height)
Definition at line 80 of file TurtleImage.java.
References view.turtle.TurtleImage.DEFAULT_SPEED, view.turtle.TurtleImage.initializeMenu(), view.turtle.TurtleImage.installStateTooltip(), view.turtle.TurtleImage.mathCoordsToCanvasCoords(), and view.turtle.TurtleImage.resize().
Member Function Documentation
void view.turtle.TurtleImage.addUpdate (TurtleUpdate tu)
Definition at line 153 of file TurtleImage.java.
References view.turtle.TurtleImage.popUpdate().
void view.turtle.TurtleImage.animatedMove (double toAngle, Point2D toLocation) private
Definition at line 215 of file TurtleImage.java.
References view.turtle.TurtleImage.createRotateTransition(), view.turtle.TurtleImage.createTranslateTransition(), and view.turtle.TurtleImage.popUpdate().
Referenced by view.turtle.TurtleImage.processUpdate().
Point2D view.turtle.TurtleImage.canvasCoordsToMathCoords (Point2D canvasCoords) private
Definition at line 422 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.installStateTooltip().
void view.turtle.TurtleImage.changeImage (Image img)
Definition at line 116 of file TurtleImage.java.
void view.turtle.TurtleImage.changeImage (String imagePath)
Definition at line 121 of file TurtleImage.java.
References view.turtle.TurtleImage.changeImage.
void view.turtle.TurtleImage.changeImage (File file)
Definition at line 125 of file TurtleImage.java.
References view.turtle.TurtleImage.changeImage.
void view.turtle.TurtleImage.clearStamps ()
Definition at line 439 of file TurtleImage.java.
Transition view.turtle.TurtleImage.createRotateTransition (double destination) private
Definition at line 278 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.animatedMove().
Transition view.turtle.TurtleImage.createTranslateTransition (Point2D destination) private
Definition at line 286 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.animatedMove().
Node view.turtle.TurtleImage.getStamps ()
Definition at line 444 of file TurtleImage.java.
References view.turtle.TurtleImage.myStamps.
void view.turtle.TurtleImage.hide (boolean hidden)
Definition at line 110 of file TurtleImage.java.
References view.turtle.TurtleImage.myImage.
Referenced by view.turtle.TurtleImage.processUpdate(), and view.turtle.TurtleImage.toggleTurtle().
void view.turtle.TurtleImage.initializeMenu () private
Definition at line 240 of file TurtleImage.java.
References view.turtle.TurtleImage.makeMenuItem(), view.turtle.TurtleImage.popMyMenu(), view.turtle.TurtleImage.selectImageFile(), view.turtle.TurtleImage.selectPenColor(), view.turtle.TurtleImage.setLineStyleMenu(), view.turtle.TurtleImage.setLineWidthMenu(), view.turtle.TurtleImage.setPenUpDown(), and view.turtle.TurtleImage.toggleTurtle().
Referenced by view.turtle.TurtleImage.TurtleImage().
void view.turtle.TurtleImage.installStateTooltip () private
Definition at line 296 of file TurtleImage.java.
References view.turtle.TurtleImage.canvasCoordsToMathCoords().
Referenced by view.turtle.TurtleImage.TurtleImage().
void view.turtle.TurtleImage.leaveStamp () private
Definition at line 429 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.processUpdate().
MenuItem view.turtle.TurtleImage.makeMenuItem (String label, EventHandler< ActionEvent > event) private
Definition at line 272 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.initializeMenu().
Point2D view.turtle.TurtleImage.mathCoordsToCanvasCoords (Point2D mathCoords) private
Definition at line 414 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.processUpdate(), and view.turtle.TurtleImage.TurtleImage().
void view.turtle.TurtleImage.popMyMenu () private
Definition at line 268 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.initializeMenu().
void view.turtle.TurtleImage.popUpdate ()
Definition at line 162 of file TurtleImage.java.
References view.turtle.TurtleImage.processUpdate().
Referenced by view.turtle.TurtleImage.addUpdate(), view.turtle.TurtleImage.animatedMove(), view.components.TurtleWindow.stepDebug(), and view.turtle.TurtleImage.unanimatedMove().
void view.turtle.TurtleImage.processUpdate (TurtleUpdate tu)
Definition at line 173 of file TurtleImage.java.
References view.turtle.TurtleImage.animatedMove(), view.turtle.TurtleImage.changeImage, view.turtle.TurtlePen.drawLine(), model.Angle.getAngleValue(), view.components.Palette.getColor(), view.turtle.TurtlePen.getColorIndex(), view.components.Palette.getImage(), model.TurtleUpdate.getShapeID(), model.TurtleUpdate.getTurtleAngle(), model.TurtleUpdate.getTurtleNewCoordinates(), model.TurtleUpdate.getTurtleOldCoordinates(), model.Coordinates.getY(), view.turtle.TurtleImage.hide(), model.TurtleUpdate.isStamp(), model.TurtleUpdate.isTurtleClear(), model.TurtleUpdate.isTurtleHidden(), model.TurtleUpdate.isTurtleInactive(), model.TurtleUpdate.isTurtlePenUp(), view.turtle.TurtleImage.leaveStamp(), view.turtle.TurtleImage.mathCoordsToCanvasCoords(), view.turtle.TurtleImage.unanimatedMove(), and view.turtle.TurtlePen.updatePen().
Referenced by view.turtle.TurtleImage.popUpdate().
void view.turtle.TurtleImage.resize (double width, double height)
Definition at line 129 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.TurtleImage().
void view.turtle.TurtleImage.selectImageFile () private
Definition at line 320 of file TurtleImage.java.
References view.turtle.TurtleImage.changeImage.
Referenced by view.turtle.TurtleImage.initializeMenu().
void view.turtle.TurtleImage.selectPenColor () private
Definition at line 311 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.initializeMenu().
void view.turtle.TurtleImage.setAnimationSpeed (double speed)
Definition at line 410 of file TurtleImage.java.
void view.turtle.TurtleImage.setDebugMode ()
Definition at line 136 of file TurtleImage.java.
Referenced by view.components.TurtleWindow.enterDebugMode().
void view.turtle.TurtleImage.setLineStyleMenu () private
Generates a toggle group for line styles (solid, dashed, dotted, dash-dot)
Definition at line 359 of file TurtleImage.java.
References view.turtle.TurtlePen.setDashDot(), view.turtle.TurtlePen.setDashed(), view.turtle.TurtlePen.setDotted(), and view.turtle.TurtlePen.setSolid().
Referenced by view.turtle.TurtleImage.initializeMenu().
void view.turtle.TurtleImage.setLineWidthMenu () private
Generates a toggle group for line width from 1-10
Definition at line 395 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.initializeMenu().
void view.turtle.TurtleImage.setPenProperties (PenUpdate pu)
Definition at line 144 of file TurtleImage.java.
References view.components.Palette.getColor(), view.turtle.TurtlePen.getColorIndex(), model.PenUpdate.getPenColorIDProperty(), model.PenUpdate.getPenSizeProperty(), view.turtle.TurtlePen.setProperties(), and view.turtle.TurtlePen.updatePen().
void view.turtle.TurtleImage.setPenUpDown () private
Definition at line 344 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.initializeMenu().
void view.turtle.TurtleImage.setRunMode ()
Definition at line 140 of file TurtleImage.java.
Referenced by view.components.TurtleWindow.exitDebugMode().
void view.turtle.TurtleImage.toggleTurtle () private
Definition at line 332 of file TurtleImage.java.
References view.turtle.TurtleImage.hide().
Referenced by view.turtle.TurtleImage.initializeMenu().
void view.turtle.TurtleImage.unanimatedMove (double toAngle, Point2D toLocation) private
Definition at line 231 of file TurtleImage.java.
References view.turtle.TurtleImage.popUpdate().
Referenced by view.turtle.TurtleImage.processUpdate().
void view.turtle.TurtleImage.updatePalette (Palette p)
Definition at line 149 of file TurtleImage.java.
Referenced by view.components.TurtleWindow.update().
Member Data Documentation
Boolean view.turtle.TurtleImage.active private
Definition at line 51 of file TurtleImage.java.
final double view.turtle.TurtleImage.ANIMATION_THRESHOLD = 1.5 static private
Definition at line 73 of file TurtleImage.java.
boolean view.turtle.TurtleImage.busy private
Definition at line 46 of file TurtleImage.java.
MenuItem view.turtle.TurtleImage.changeImage private
Definition at line 59 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.changeImage(), view.turtle.TurtleImage.processUpdate(), and view.turtle.TurtleImage.selectImageFile().
ContextMenu view.turtle.TurtleImage.contextMenu private
Definition at line 58 of file TurtleImage.java.
boolean view.turtle.TurtleImage.debugMode private
Definition at line 47 of file TurtleImage.java.
final double view.turtle.TurtleImage.DEFAULT_HEIGHT = 30 static private
Definition at line 71 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.TurtleImage().
final String view.turtle.TurtleImage.DEFAULT_IMAGEPATH = "/resources/images/turtle-top-view.png" static private
Definition at line 69 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.TurtleImage().
final double view.turtle.TurtleImage.DEFAULT_SPEED = 0.6 static private
Definition at line 72 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.TurtleImage().
final double view.turtle.TurtleImage.DEFAULT_WIDTH = 30 static private
Definition at line 70 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.TurtleImage().
final double view.turtle.TurtleImage.DEFAULT_XPOS = 0 static private
Definition at line 67 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.TurtleImage().
final double view.turtle.TurtleImage.DEFAULT_YPOS = 0 static private
Definition at line 68 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.TurtleImage().
GraphicsContext view.turtle.TurtleImage.gc private
Definition at line 39 of file TurtleImage.java.
Menu view.turtle.TurtleImage.lineStyle private
Definition at line 62 of file TurtleImage.java.
Menu view.turtle.TurtleImage.lineWidth private
Definition at line 63 of file TurtleImage.java.
double view.turtle.TurtleImage.myHeight private
Definition at line 44 of file TurtleImage.java.
int view.turtle.TurtleImage.myID private
Definition at line 42 of file TurtleImage.java.
Image view.turtle.TurtleImage.myImage private
Definition at line 38 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.hide().
Palette view.turtle.TurtleImage.myPalette private
Definition at line 49 of file TurtleImage.java.
TurtlePen view.turtle.TurtleImage.myPen private
Definition at line 40 of file TurtleImage.java.
double view.turtle.TurtleImage.mySpeed private
Definition at line 45 of file TurtleImage.java.
Group view.turtle.TurtleImage.myStamps private
Definition at line 55 of file TurtleImage.java.
Referenced by view.turtle.TurtleImage.getStamps().
double view.turtle.TurtleImage.myWidth private
Definition at line 43 of file TurtleImage.java.
MenuItem view.turtle.TurtleImage.penColor private
Definition at line 61 of file TurtleImage.java.
PriorityQueue<TurtleUpdate> view.turtle.TurtleImage.pendingUpdates private
Definition at line 48 of file TurtleImage.java.
Boolean view.turtle.TurtleImage.penUp private
Definition at line 53 of file TurtleImage.java.
MenuItem view.turtle.TurtleImage.penUpDown private
Definition at line 64 of file TurtleImage.java.
MenuItem view.turtle.TurtleImage.toggle private
Definition at line 60 of file TurtleImage.java.
Boolean view.turtle.TurtleImage.visible private
Definition at line 52 of file TurtleImage.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/turtle/TurtleImage.java