slogo_team17: view.toolbar.TurtlePenColorToolbarItem Class Reference
view.toolbar.TurtlePenColorToolbarItem Class Reference
Public Member Functions
void changeTurtleProperties (int turtleID)
Public Member Functions inherited from view.toolbar.TurtleSpecificToolbarItem
abstract void changeTurtleProperties (int turtleID)
Protected Member Functions
TurtlePenColorToolbarItem (String label, Toolbar tb)
Node createNode ()
Protected Member Functions inherited from view.toolbar.TurtleSpecificToolbarItem
TurtleSpecificToolbarItem (String label, Toolbar tb)
void getAndModifyTurtles ()
Protected Member Functions inherited from view.toolbar.ToolbarItem
ToolbarItem (String label, Toolbar container)
void setLabel (String label)
abstract Node createNode ()
Private Attributes
Color color
Additional Inherited Members
Protected Attributes inherited from view.toolbar.ToolbarItem
Toolbar myToolbar
Node myNode
Label myLabel
Static Protected Attributes inherited from view.toolbar.TurtleSpecificToolbarItem
static final String TURTLE_PROMPT
Package Attributes inherited from view.toolbar.TurtleSpecificToolbarItem
List< Integer > selectedTurtles
Detailed Description
Toolbar Item to change pen color.
Author
lien
Definition at line 13 of file TurtlePenColorToolbarItem.java.
Constructor & Destructor Documentation
view.toolbar.TurtlePenColorToolbarItem.TurtlePenColorToolbarItem (String label, Toolbar tb) protected
Definition at line 17 of file TurtlePenColorToolbarItem.java.
Member Function Documentation
void view.toolbar.TurtlePenColorToolbarItem.changeTurtleProperties (int turtleID)
Definition at line 22 of file TurtlePenColorToolbarItem.java.
References view.components.TurtleWindow.changePenColor(), view.toolbar.Toolbar.getTurtleWindow(), and view.toolbar.ToolbarItem.myToolbar.
Node view.toolbar.TurtlePenColorToolbarItem.createNode () protected
Definition at line 28 of file TurtlePenColorToolbarItem.java.
References view.toolbar.TurtleSpecificToolbarItem.getAndModifyTurtles().
Member Data Documentation
Color view.toolbar.TurtlePenColorToolbarItem.color private
Definition at line 15 of file TurtlePenColorToolbarItem.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/toolbar/TurtlePenColorToolbarItem.java