slogo_team17: view.View Class Reference
view.View Class Reference
Public Member Functions
View (Stage stage)
void showHelp ()
void showAndChangeLanguage ()
void showDialog (String message)
void addNewTab ()
void showView ()
void saveCurrentLibrary ()
void loadLibrary ()
void addDebuger ()
void removeDebuger ()
void runDebugger ()
TurtleWindow getTurtleWindow ()
VariablesWindow getVariablesWindow ()
CommandsHistoryWindow getCommandHistoryWindow ()
UserDefinedCommandsWindow getUDCommandsWindow ()
String getTabTitle ()
void setTabTitle (String title)
Static Public Member Functions
static View getInstance ()
Private Member Functions
void addTopBars ()
void generateProgramDialogs ()
void tabChangeUpdate ()
String promptFileToSave ()
Private Attributes
Stage myStage
Scene myScene
BorderPane myBorderPane
SLogoMenuBar myMenuBar
TabPane myTabPane
int myActiveTab
int numTabs
HelpDialogBox myHelpBox
LanguagesDialogBox myLanguagesBox
Static Private Attributes
static View instance
static final String TITLE = "SLOGO"
static final Color BACKGROUND_COLOR = Color.LIGHTGREY
Detailed Description
Singleton class responsible for setting up the GUI, and handling user interactions.
Author
lien
Definition at line 49 of file View.java.
Constructor & Destructor Documentation
view.View.View (Stage stage)
Definition at line 68 of file View.java.
References view.View.addNewTab(), view.View.addTopBars(), view.View.generateProgramDialogs(), and view.Main.SIZE.
Member Function Documentation
void view.View.addDebuger ()
Definition at line 217 of file View.java.
References view.components.SLogoWorkspace.startDebugger().
Referenced by view.components.CommandPort.enterDebugMode().
void view.View.addNewTab ()
Definition at line 133 of file View.java.
References view.View.tabChangeUpdate().
Referenced by view.components.SLogoMenuBar.makeFileMenu(), and view.View.View().
void view.View.addTopBars () private
Constructs a menu bar and a tabpane to be placed at the top
Definition at line 96 of file View.java.
References view.View.tabChangeUpdate().
Referenced by view.View.View().
void view.View.generateProgramDialogs () private
Definition at line 113 of file View.java.
Referenced by view.View.View().
CommandsHistoryWindow view.View.getCommandHistoryWindow ()
Definition at line 240 of file View.java.
Referenced by model.State.State().
static View view.View.getInstance () static
Definition at line 257 of file View.java.
Referenced by model.TurtleMultiple.addNewTurtle(), view.components.CommandPort.enterDebugMode(), view.components.DebuggerPort.exitDebugMode(), view.listwindows.CommandsListWindow.parseCommand(), view.components.CommandPort.runCommand(), model.VariableString.setValue(), model.State.State(), and view.components.DebuggerPort.stepDebug().
String view.View.getTabTitle ()
Definition at line 248 of file View.java.
TurtleWindow view.View.getTurtleWindow ()
Definition at line 232 of file View.java.
Referenced by model.TurtleMultiple.addNewTurtle(), view.components.SLogoMenuBar.makePreferencesMenu(), and model.State.State().
UserDefinedCommandsWindow view.View.getUDCommandsWindow ()
Definition at line 244 of file View.java.
Referenced by model.State.State().
VariablesWindow view.View.getVariablesWindow ()
Definition at line 236 of file View.java.
Referenced by model.State.State().
void view.View.loadLibrary ()
Definition at line 182 of file View.java.
References model.Model.getInstance(), and model.Model.parse().
String view.View.promptFileToSave () private
Definition at line 203 of file View.java.
References view.dialogs.InputDialogBox.showInputDialog().
void view.View.removeDebuger ()
Definition at line 222 of file View.java.
References view.components.SLogoWorkspace.stopDebugger().
Referenced by view.components.DebuggerPort.exitDebugMode().
void view.View.runDebugger ()
Definition at line 227 of file View.java.
References view.components.SLogoWorkspace.runDebugger().
Referenced by view.components.DebuggerPort.stepDebug().
void view.View.saveCurrentLibrary ()
Definition at line 153 of file View.java.
References model.Model.getInstance(), and model.Model.saveLibrary().
void view.View.setTabTitle (String title)
Definition at line 252 of file View.java.
References view.components.SLogoWorkspace.setTitle().
Referenced by view.components.SLogoMenuBar.makePreferencesMenu().
void view.View.showAndChangeLanguage ()
Definition at line 122 of file View.java.
References parser.parser.Regex.changeLanguage(), parser.parser.Regex.getInstance(), and view.dialogs.InputDialogBox.showInputDialog().
Referenced by view.components.SLogoMenuBar.makePreferencesMenu().
void view.View.showDialog (String message)
Definition at line 128 of file View.java.
References view.dialogs.DialogBox.show().
Referenced by view.listwindows.CommandsListWindow.parseCommand(), view.components.CommandPort.runCommand(), and model.VariableString.setValue().
void view.View.showHelp ()
Definition at line 118 of file View.java.
References view.dialogs.DialogBox.show().
Referenced by view.components.SLogoMenuBar.makeHelpMenu().
void view.View.showView ()
Definition at line 149 of file View.java.
Referenced by view.Main.start().
void view.View.tabChangeUpdate () private
Definition at line 143 of file View.java.
References parser.parser.Regex.changeLanguage(), parser.parser.Regex.getInstance(), model.Model.getInstance(), and model.Model.setState().
Referenced by view.View.addNewTab(), and view.View.addTopBars().
Member Data Documentation
final Color view.View.BACKGROUND_COLOR = Color.LIGHTGREY static private
Definition at line 66 of file View.java.
View view.View.instance static private
Definition at line 50 of file View.java.
int view.View.myActiveTab private
Definition at line 59 of file View.java.
BorderPane view.View.myBorderPane private
Definition at line 54 of file View.java.
HelpDialogBox view.View.myHelpBox private
Definition at line 62 of file View.java.
LanguagesDialogBox view.View.myLanguagesBox private
Definition at line 63 of file View.java.
SLogoMenuBar view.View.myMenuBar private
Definition at line 56 of file View.java.
Scene view.View.myScene private
Definition at line 53 of file View.java.
Stage view.View.myStage private
Definition at line 52 of file View.java.
TabPane view.View.myTabPane private
Definition at line 57 of file View.java.
int view.View.numTabs private
Definition at line 60 of file View.java.
final String view.View.TITLE = "SLOGO" static private
Definition at line 65 of file View.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/View.java