slogo_team17: view.toolbar.Toolbar Class Reference
view.toolbar.Toolbar Class Reference
Public Member Functions
Toolbar ()
void setTurtleWindow (TurtleWindow tw)
TurtleWindow getTurtleWindow ()
Static Public Attributes
static final String BACKGROUND_COLOR = "Background color"
static final String ANIMATION_SPEED = "Animation speed"
static final String ADD_TURTLE = "Add turtle"
static final String TURTLE_IMAGE = "Turtle image"
static final String PEN_COLOR = "Pen color"
Private Attributes
HBox myToolbar
TurtleWindow myTurtleWindow
Detailed Description
Toolbar for the SLogo Program. Creates and arranges items to manipulate display options.
Author
lien
Definition at line 16 of file Toolbar.java.
Constructor & Destructor Documentation
view.toolbar.Toolbar.Toolbar ()
Definition at line 32 of file Toolbar.java.
References view.components.TurtleWindow.updateAnimationSpeed().
Member Function Documentation
TurtleWindow view.toolbar.Toolbar.getTurtleWindow ()
Definition at line 60 of file Toolbar.java.
References view.toolbar.Toolbar.myTurtleWindow.
Referenced by view.toolbar.TurtlePenColorToolbarItem.changeTurtleProperties(), view.toolbar.TurtleImageToolbarItem.changeTurtleProperties(), view.toolbar.AddTurtleToolbarItem.createNode(), view.toolbar.BackgroundColorToolbarItem.createNode(), view.toolbar.ShowTurtlesToolbarItem.createNode(), view.toolbar.TurtleSpecificToolbarItem.getAvailableTurtles(), and view.toolbar.TurtleSpecificToolbarItem.getUserInput().
void view.toolbar.Toolbar.setTurtleWindow (TurtleWindow tw)
Definition at line 56 of file Toolbar.java.
Referenced by view.components.SLogoWorkspace.addToolbar().
Member Data Documentation
final String view.toolbar.Toolbar.ADD_TURTLE = "Add turtle" static
Definition at line 28 of file Toolbar.java.
final String view.toolbar.Toolbar.ANIMATION_SPEED = "Animation speed" static
Definition at line 27 of file Toolbar.java.
final String view.toolbar.Toolbar.BACKGROUND_COLOR = "Background color" static
Definition at line 26 of file Toolbar.java.
HBox view.toolbar.Toolbar.myToolbar private
Definition at line 18 of file Toolbar.java.
TurtleWindow view.toolbar.Toolbar.myTurtleWindow private
Definition at line 19 of file Toolbar.java.
Referenced by view.toolbar.Toolbar.getTurtleWindow().
final String view.toolbar.Toolbar.PEN_COLOR = "Pen color" static
Definition at line 30 of file Toolbar.java.
final String view.toolbar.Toolbar.TURTLE_IMAGE = "Turtle image" static
Definition at line 29 of file Toolbar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/toolbar/Toolbar.java