slogo_team17: view.toolbar.ShowTurtlesToolbarItem Class Reference
view.toolbar.ShowTurtlesToolbarItem Class Reference
Protected Member Functions
ShowTurtlesToolbarItem (Toolbar container)
Node createNode ()
Protected Member Functions inherited from view.toolbar.ToolbarItem
ToolbarItem (String label, Toolbar container)
void setLabel (String label)
abstract Node createNode ()
Private Attributes
boolean show
Static Private Attributes
static final String SHOW = "Inactive turtles: shown "
static final String HIDE = "Inactive turtles: hidden"
Additional Inherited Members
Protected Attributes inherited from view.toolbar.ToolbarItem
Toolbar myToolbar
Node myNode
Label myLabel
Detailed Description
Definition at line 7 of file ShowTurtlesToolbarItem.java.
Constructor & Destructor Documentation
view.toolbar.ShowTurtlesToolbarItem.ShowTurtlesToolbarItem (Toolbar container) protected
Definition at line 13 of file ShowTurtlesToolbarItem.java.
Member Function Documentation
Node view.toolbar.ShowTurtlesToolbarItem.createNode () protected
Definition at line 20 of file ShowTurtlesToolbarItem.java.
References view.toolbar.Toolbar.getTurtleWindow(), view.toolbar.ToolbarItem.myToolbar, view.toolbar.ToolbarItem.setLabel(), and view.components.TurtleWindow.toggleInactiveTurtles().
Member Data Documentation
final String view.toolbar.ShowTurtlesToolbarItem.HIDE = "Inactive turtles: hidden" static private
Definition at line 10 of file ShowTurtlesToolbarItem.java.
final String view.toolbar.ShowTurtlesToolbarItem.SHOW = "Inactive turtles: shown " static private
Definition at line 9 of file ShowTurtlesToolbarItem.java.
boolean view.toolbar.ShowTurtlesToolbarItem.show private
Definition at line 11 of file ShowTurtlesToolbarItem.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/toolbar/ShowTurtlesToolbarItem.java