slogo_team17: model.ScopedVariablesCollection Class Reference
model.ScopedVariablesCollection Class Reference
Public Member Functions
ScopedVariablesCollection ()
void enterScope ()
void exitScope ()
boolean containsVariable (String varName)
Object getVariableValue (String varName)
void addVariable (String varName, String varValue) throws VariableCreationException, VariableCreationInvalidValueException
void addObserver (Observer o)
void removeObserver (Observer o)
void notifyObservers ()
String saveState ()
Private Attributes
ArrayList< VariablesCollection > collectionStack
List< Observer > myObserverList
Detailed Description
Definition at line 12 of file ScopedVariablesCollection.java.
Constructor & Destructor Documentation
model.ScopedVariablesCollection.ScopedVariablesCollection ()
Definition at line 17 of file ScopedVariablesCollection.java.
Member Function Documentation
void model.ScopedVariablesCollection.addObserver (Observer o)
Implements model.IVariablesCollection.
Definition at line 65 of file ScopedVariablesCollection.java.
void model.ScopedVariablesCollection.addVariable (String varName, String varValue) throws VariableCreationException, VariableCreationInvalidValueException
Implements model.IVariablesCollection.
Definition at line 55 of file ScopedVariablesCollection.java.
References model.ScopedVariablesCollection.notifyObservers().
Referenced by model.ScopedVariablesCollection.getVariableValue().
boolean model.ScopedVariablesCollection.containsVariable (String varName)
Definition at line 33 of file ScopedVariablesCollection.java.
void model.ScopedVariablesCollection.enterScope ()
Implements model.IVariablesCollection.
Definition at line 23 of file ScopedVariablesCollection.java.
void model.ScopedVariablesCollection.exitScope ()
Implements model.IVariablesCollection.
Definition at line 27 of file ScopedVariablesCollection.java.
References model.ScopedVariablesCollection.notifyObservers().
Object model.ScopedVariablesCollection.getVariableValue (String varName)
Implements model.IVariablesCollection.
Definition at line 41 of file ScopedVariablesCollection.java.
References model.ScopedVariablesCollection.addVariable(), and model.ScopedVariablesCollection.notifyObservers().
void model.ScopedVariablesCollection.notifyObservers ()
Implements model.IVariablesCollection.
Definition at line 75 of file ScopedVariablesCollection.java.
References model.VariablesCollectionUpdate.getDisplayProperties(), and model.VariablesCollectionUpdate.getNameProperties().
Referenced by model.ScopedVariablesCollection.addVariable(), model.ScopedVariablesCollection.exitScope(), and model.ScopedVariablesCollection.getVariableValue().
void model.ScopedVariablesCollection.removeObserver (Observer o)
Implements model.IVariablesCollection.
Definition at line 70 of file ScopedVariablesCollection.java.
String model.ScopedVariablesCollection.saveState ()
Concatenates a String that contains all the necessary variable declarations to recreate the variable collection, for the purpose of saving.
Implements model.IVariablesCollection.
Definition at line 91 of file ScopedVariablesCollection.java.
Member Data Documentation
ArrayList<VariablesCollection> model.ScopedVariablesCollection.collectionStack private
Definition at line 14 of file ScopedVariablesCollection.java.
List<Observer> model.ScopedVariablesCollection.myObserverList private
Definition at line 15 of file ScopedVariablesCollection.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/ScopedVariablesCollection.java