slogo_team17: model.Variable Class Reference
model.Variable Class Reference abstract
Public Member Functions
Variable (String name)
abstract Object getValue ()
abstract void setValue (String edit) throws VariableWrongTypeException
Protected Member Functions
StringProperty getStringProperty ()
StringProperty getNameProperty ()
Protected Attributes
StringProperty myDisplayProperty
StringProperty myNameProperty
Detailed Description
Definition at line 7 of file Variable.java.
Constructor & Destructor Documentation
model.Variable.Variable (String name)
Definition at line 11 of file Variable.java.
Member Function Documentation
StringProperty model.Variable.getNameProperty () protected
Definition at line 33 of file Variable.java.
References model.Variable.myNameProperty.
Referenced by model.VariableInt.clone(), model.VariableString.clone(), and model.VariableDouble.clone().
StringProperty model.Variable.getStringProperty () protected
Returns a string of the variable's value. This String is binded to the Variable's real property, and this StringProperty is handed to the front end.
Definition at line 30 of file Variable.java.
References model.Variable.myDisplayProperty.
abstract Object model.Variable.getValue () abstract
Returns a nondestructible value.
Referenced by model.VariablesCollection.getVariableValue().
abstract void model.Variable.setValue (String edit) throws VariableWrongTypeException abstract
This method is used to attempt to change the value (but NOT type) of the variable to a different value, edit.
Exceptions
VariableWrongTypeException if edit is not of the same type as the variable's value
Referenced by model.VariablesCollection.addVariable().
Member Data Documentation
StringProperty model.Variable.myDisplayProperty protected
Definition at line 8 of file Variable.java.
Referenced by model.Variable.getStringProperty(), model.VariableDouble.VariableDouble(), model.VariableInt.VariableInt(), and model.VariableString.VariableString().
StringProperty model.Variable.myNameProperty protected
Definition at line 9 of file Variable.java.
Referenced by model.Variable.getNameProperty().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/Variable.java