slogo_team17: model.CommandHistory Class Reference
model.CommandHistory Class Reference
Public Member Functions
CommandHistory ()
void addCommand (CommandRoot cr)
ToData getUDCommand (String name) throws UDCommandNotFoundException
boolean addUDCommand (ToData udCommand)
List< String > getCommandList ()
List< String > getUDCommandList ()
String saveUDCommands ()
void addObserver (Observer o)
void removeObserver (Observer o)
void notifyObservers ()
Private Attributes
List< CommandRoot > myCommandList
List< Observer > myObserverList
List< ToData > myUDCommands
Detailed Description
Keeps account of commands already run, and user defined commands.
Definition at line 16 of file CommandHistory.java.
Constructor & Destructor Documentation
model.CommandHistory.CommandHistory ()
Definition at line 21 of file CommandHistory.java.
Member Function Documentation
void model.CommandHistory.addCommand (CommandRoot cr)
To add command to command history.
Definition at line 30 of file CommandHistory.java.
References model.CommandHistory.notifyObservers().
Referenced by model.Model.parse().
void model.CommandHistory.addObserver (Observer o)
Implements model.Observable.
Definition at line 101 of file CommandHistory.java.
Referenced by model.State.State().
boolean model.CommandHistory.addUDCommand (ToData udCommand)
Adds a newly created UD command.
Definition at line 50 of file CommandHistory.java.
References parser.commands.ToData.getName().
Referenced by parser.commands.ToData.execute().
List<String> model.CommandHistory.getCommandList ()
Prepares a String list of all the existing commands in the history to send to the front end.
Returns
Definition at line 63 of file CommandHistory.java.
Referenced by model.CommandHistoryUpdate.CommandHistoryUpdate().
ToData model.CommandHistory.getUDCommand (String name) throws UDCommandNotFoundException
Attempts to find an existing UD command by name.
Definition at line 38 of file CommandHistory.java.
List<String> model.CommandHistory.getUDCommandList ()
Prepares a String list of UD command displays to send to the front end.
Definition at line 74 of file CommandHistory.java.
Referenced by model.CommandHistoryUpdate.CommandHistoryUpdate().
void model.CommandHistory.notifyObservers ()
Implements model.Observable.
Definition at line 111 of file CommandHistory.java.
Referenced by model.CommandHistory.addCommand().
void model.CommandHistory.removeObserver (Observer o)
Implements model.Observable.
Definition at line 106 of file CommandHistory.java.
String model.CommandHistory.saveUDCommands ()
Concatenates all UD command declarations into a single string, for the purpose of saving.
Definition at line 91 of file CommandHistory.java.
Member Data Documentation
List<CommandRoot> model.CommandHistory.myCommandList private
Definition at line 17 of file CommandHistory.java.
List<Observer> model.CommandHistory.myObserverList private
Definition at line 18 of file CommandHistory.java.
List<ToData> model.CommandHistory.myUDCommands private
Definition at line 19 of file CommandHistory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/CommandHistory.java