slogo_team17: model.ViewOptions Class Reference
model.ViewOptions Class Reference
Public Member Functions
ViewOptions ()
void initialize ()
IntegerProperty getBackgroundID ()
int getPaletteB ()
int getPaletteG ()
int getPaletteR ()
boolean isClear ()
boolean isClearStamps ()
void setBackgroundID (int backgroundID)
void setClear (boolean isClear)
void setClearStamps (boolean isClearStamps)
void setPaletteB (int r, int g, int b, int index) throws InvalidViewSettingException
void setStampsOut (boolean b)
boolean isStampsOut ()
void addObserver (Observer o)
void removeObserver (Observer o)
void notifyObservers ()
void notifyObservers (Object obj)
int getPaletteIndex ()
Package Attributes
int paletteG
int paletteB
int paletteIndex
boolean isClearStamps
boolean isStampsOut
Private Attributes
IntegerProperty backgroundIDProperty
int paletteR
boolean isClear
List< Observer > myObservers
Detailed Description
Container class for information that is not particular to any one turtle.
Definition at line 14 of file ViewOptions.java.
Constructor & Destructor Documentation
model.ViewOptions.ViewOptions ()
Definition at line 20 of file ViewOptions.java.
Member Function Documentation
void model.ViewOptions.addObserver (Observer o)
Implements model.Observable.
Definition at line 88 of file ViewOptions.java.
Referenced by model.State.State().
IntegerProperty model.ViewOptions.getBackgroundID ()
Implements model.ViewInitializer.
Definition at line 29 of file ViewOptions.java.
int model.ViewOptions.getPaletteB ()
Implements model.ViewUpdate.
Definition at line 34 of file ViewOptions.java.
References model.ViewOptions.paletteB.
int model.ViewOptions.getPaletteG ()
Implements model.ViewUpdate.
Definition at line 37 of file ViewOptions.java.
References model.ViewOptions.paletteG.
int model.ViewOptions.getPaletteIndex ()
Implements model.ViewUpdate.
Definition at line 111 of file ViewOptions.java.
References model.ViewOptions.paletteIndex.
int model.ViewOptions.getPaletteR ()
Implements model.ViewUpdate.
Definition at line 40 of file ViewOptions.java.
References model.ViewOptions.paletteR.
void model.ViewOptions.initialize ()
Definition at line 25 of file ViewOptions.java.
References model.ViewOptions.notifyObservers().
Referenced by model.State.State().
boolean model.ViewOptions.isClear ()
Implements model.ViewUpdate.
Definition at line 44 of file ViewOptions.java.
Referenced by model.ViewOptions.setClear().
boolean model.ViewOptions.isClearStamps ()
Implements model.ViewUpdate.
Definition at line 49 of file ViewOptions.java.
Referenced by model.ViewOptions.setClearStamps().
boolean model.ViewOptions.isStampsOut ()
Definition at line 80 of file ViewOptions.java.
void model.ViewOptions.notifyObservers ()
Implements model.Observable.
Definition at line 98 of file ViewOptions.java.
Referenced by model.ViewOptions.initialize(), model.ViewOptions.setBackgroundID(), model.ViewOptions.setClear(), model.ViewOptions.setClearStamps(), and model.ViewOptions.setPaletteB().
void model.ViewOptions.notifyObservers (Object obj)
Definition at line 104 of file ViewOptions.java.
void model.ViewOptions.removeObserver (Observer o)
Implements model.Observable.
Definition at line 93 of file ViewOptions.java.
void model.ViewOptions.setBackgroundID (int backgroundID)
Definition at line 53 of file ViewOptions.java.
References model.ViewOptions.notifyObservers().
void model.ViewOptions.setClear (boolean isClear)
Definition at line 57 of file ViewOptions.java.
References model.ViewOptions.isClear(), and model.ViewOptions.notifyObservers().
void model.ViewOptions.setClearStamps (boolean isClearStamps)
Definition at line 61 of file ViewOptions.java.
References model.ViewOptions.isClearStamps(), and model.ViewOptions.notifyObservers().
void model.ViewOptions.setPaletteB (int r, int g, int b, int index) throws InvalidViewSettingException
Definition at line 65 of file ViewOptions.java.
References model.ViewOptions.notifyObservers().
void model.ViewOptions.setStampsOut (boolean b)
Definition at line 76 of file ViewOptions.java.
Member Data Documentation
IntegerProperty model.ViewOptions.backgroundIDProperty private
Definition at line 15 of file ViewOptions.java.
boolean model.ViewOptions.isClear private
Definition at line 17 of file ViewOptions.java.
boolean model.ViewOptions.isClearStamps package
Definition at line 17 of file ViewOptions.java.
boolean model.ViewOptions.isStampsOut package
Definition at line 17 of file ViewOptions.java.
List<Observer> model.ViewOptions.myObservers private
Definition at line 18 of file ViewOptions.java.
int model.ViewOptions.paletteB package
Definition at line 16 of file ViewOptions.java.
Referenced by model.ViewOptions.getPaletteB().
int model.ViewOptions.paletteG package
Definition at line 16 of file ViewOptions.java.
Referenced by model.ViewOptions.getPaletteG().
int model.ViewOptions.paletteIndex package
Definition at line 16 of file ViewOptions.java.
Referenced by model.ViewOptions.getPaletteIndex().
int model.ViewOptions.paletteR private
Definition at line 16 of file ViewOptions.java.
Referenced by model.ViewOptions.getPaletteR().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/ViewOptions.java