slogo_team17: view.dialogs.LanguagesDialogBox Class Reference
view.dialogs.LanguagesDialogBox Class Reference
Public Member Functions
LanguagesDialogBox ()
Public Member Functions inherited from view.dialogs.InputDialogBox
InputDialogBox (String prompt)
Object showInputDialog ()
Public Member Functions inherited from view.dialogs.MessageDialogBox
MessageDialogBox (String message)
Public Member Functions inherited from view.dialogs.DialogBox
DialogBox ()
void show ()
Protected Member Functions
void addInputField ()
void updateUserInput ()
Protected Member Functions inherited from view.dialogs.InputDialogBox
abstract void addInputField ()
abstract void updateUserInput ()
Protected Member Functions inherited from view.dialogs.DialogBox
void setTitle (String title)
Private Member Functions
void populateChoiceBox ()
Private Attributes
ChoiceBox< String > langChoiceBox
List< String > availableLanguages
Static Private Attributes
static final String LANGUAGE_PROMPT = "Please choose your language:"
Additional Inherited Members
Protected Attributes inherited from view.dialogs.InputDialogBox
Object userInput
Protected Attributes inherited from view.dialogs.DialogBox
Stage myStage
Scene myScene
BorderPane myPane
String myTitle
Detailed Description
Definition at line 12 of file LanguagesDialogBox.java.
Constructor & Destructor Documentation
view.dialogs.LanguagesDialogBox.LanguagesDialogBox ()
Definition at line 18 of file LanguagesDialogBox.java.
References view.components.LanguageController.getAvailableLanguages(), and view.dialogs.LanguagesDialogBox.populateChoiceBox().
Member Function Documentation
void view.dialogs.LanguagesDialogBox.addInputField () protected
Definition at line 26 of file LanguagesDialogBox.java.
References view.dialogs.DialogBox.myPane, and view.dialogs.InputDialogBox.userInput.
void view.dialogs.LanguagesDialogBox.populateChoiceBox () private
Definition at line 45 of file LanguagesDialogBox.java.
Referenced by view.dialogs.LanguagesDialogBox.LanguagesDialogBox().
void view.dialogs.LanguagesDialogBox.updateUserInput () protected
Definition at line 51 of file LanguagesDialogBox.java.
Member Data Documentation
List<String> view.dialogs.LanguagesDialogBox.availableLanguages private
Definition at line 15 of file LanguagesDialogBox.java.
ChoiceBox<String> view.dialogs.LanguagesDialogBox.langChoiceBox private
Definition at line 14 of file LanguagesDialogBox.java.
final String view.dialogs.LanguagesDialogBox.LANGUAGE_PROMPT = "Please choose your language:" static private
Definition at line 16 of file LanguagesDialogBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/dialogs/LanguagesDialogBox.java