slogo_team17: view.listwindows.VariableLabel Class Reference
view.listwindows.VariableLabel Class Reference
Public Member Functions
VariableLabel (StringProperty myName, StringProperty myValue)
void startEdit ()
void exitEdit ()
void processEdit (KeyEvent e)
Package Attributes
Label myVarLabel
StringProperty myName
Label myValueLabel
StringProperty myValue
TextField myTextField
Detailed Description
Definition at line 10 of file VariableLabel.java.
Constructor & Destructor Documentation
view.listwindows.VariableLabel.VariableLabel (StringProperty myName, StringProperty myValue)
Definition at line 17 of file VariableLabel.java.
References view.listwindows.VariableLabel.myValue, and view.listwindows.VariableLabel.startEdit().
Member Function Documentation
void view.listwindows.VariableLabel.exitEdit ()
Definition at line 33 of file VariableLabel.java.
Referenced by view.listwindows.VariableLabel.processEdit(), and view.listwindows.VariableLabel.startEdit().
void view.listwindows.VariableLabel.processEdit (KeyEvent e)
Definition at line 38 of file VariableLabel.java.
References view.listwindows.VariableLabel.exitEdit().
Referenced by view.listwindows.VariableLabel.startEdit().
void view.listwindows.VariableLabel.startEdit ()
Definition at line 25 of file VariableLabel.java.
References view.listwindows.VariableLabel.exitEdit(), and view.listwindows.VariableLabel.processEdit().
Referenced by view.listwindows.VariableLabel.VariableLabel().
Member Data Documentation
StringProperty view.listwindows.VariableLabel.myName package
Definition at line 12 of file VariableLabel.java.
TextField view.listwindows.VariableLabel.myTextField package
Definition at line 15 of file VariableLabel.java.
StringProperty view.listwindows.VariableLabel.myValue package
Definition at line 14 of file VariableLabel.java.
Referenced by view.listwindows.VariableLabel.VariableLabel().
Label view.listwindows.VariableLabel.myValueLabel package
Definition at line 13 of file VariableLabel.java.
Label view.listwindows.VariableLabel.myVarLabel package
Definition at line 11 of file VariableLabel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/listwindows/VariableLabel.java