slogo_team17: view.listwindows.UserDefinedCommandsWindow Class Reference
view.listwindows.UserDefinedCommandsWindow Class Reference
Public Member Functions
UserDefinedCommandsWindow (int w, int h)
Public Member Functions inherited from view.listwindows.CommandsListWindow
CommandsListWindow (int w, int h, String label)
void update (Object o)
void parseCommand (String command)
Public Member Functions inherited from view.listwindows.ListWindow
ListWindow (int w, int h, String label)
Protected Member Functions
List< String > getCommandsList (CommandHistoryUpdate chu)
void setButtonAction (Button commandButton)
Protected Member Functions inherited from view.listwindows.CommandsListWindow
abstract List< String > getCommandsList (CommandHistoryUpdate chu)
abstract void setButtonAction (Button commandButton)
Private Attributes
TextInputDialogBox myParamPromptBox
Static Private Attributes
static final String UD_COMMANDS = "User Defined Commands"
static final String PARAM_PROMPT = "Add parameter(s) to complete the command:"
Additional Inherited Members
Protected Attributes inherited from view.listwindows.ListWindow
BorderPane myPane
Label myLabel
VBox myList
ScrollPane myScrollPane
int width
int height
Detailed Description
Definition at line 9 of file UserDefinedCommandsWindow.java.
Constructor & Destructor Documentation
view.listwindows.UserDefinedCommandsWindow.UserDefinedCommandsWindow (int w, int h)
Definition at line 15 of file UserDefinedCommandsWindow.java.
Member Function Documentation
List<String> view.listwindows.UserDefinedCommandsWindow.getCommandsList (CommandHistoryUpdate chu) protected
Definition at line 22 of file UserDefinedCommandsWindow.java.
References model.CommandHistoryUpdate.getUDCommand().
void view.listwindows.UserDefinedCommandsWindow.setButtonAction (Button commandButton) protected
Definition at line 28 of file UserDefinedCommandsWindow.java.
References view.listwindows.CommandsListWindow.parseCommand(), view.dialogs.TextInputDialogBox.setText(), and view.dialogs.InputDialogBox.showInputDialog().
Member Data Documentation
TextInputDialogBox view.listwindows.UserDefinedCommandsWindow.myParamPromptBox private
Definition at line 13 of file UserDefinedCommandsWindow.java.
final String view.listwindows.UserDefinedCommandsWindow.PARAM_PROMPT = "Add parameter(s) to complete the command:" static private
Definition at line 12 of file UserDefinedCommandsWindow.java.
final String view.listwindows.UserDefinedCommandsWindow.UD_COMMANDS = "User Defined Commands" static private
Definition at line 11 of file UserDefinedCommandsWindow.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/listwindows/UserDefinedCommandsWindow.java