slogo_team17: view.components.Palette Class Reference
view.components.Palette Class Reference
Public Member Functions
Palette ()
void addImage (ImageIndex...imageIndexs)
void addColor (ColorIndex...colorIndexs)
void updateImage (int index, ImageIndex imgx)
void updateColor (int index, ColorIndex colx)
void updateColor (int index, int r, int g, int b)
Image getImage (int index)
Color getColor (int index)
ArrayList< ImageIndex > getImageList ()
ArrayList< ColorIndex > getColorList ()
int imageListSize ()
int colorListSize ()
Private Attributes
ArrayList< ImageIndex > myImagePalettes
ArrayList< ColorIndex > myColorPalettes
Detailed Description
Definition at line 8 of file Palette.java.
Constructor & Destructor Documentation
view.components.Palette.Palette ()
Definition at line 12 of file Palette.java.
Member Function Documentation
void view.components.Palette.addColor (ColorIndex... colorIndexs)
Definition at line 23 of file Palette.java.
Referenced by view.components.Palette.updateColor().
void view.components.Palette.addImage (ImageIndex... imageIndexs)
Definition at line 17 of file Palette.java.
Referenced by view.components.Palette.updateImage().
int view.components.Palette.colorListSize ()
Definition at line 76 of file Palette.java.
Color view.components.Palette.getColor (int index)
Definition at line 57 of file Palette.java.
Referenced by view.turtle.TurtleImage.processUpdate(), and view.turtle.TurtleImage.setPenProperties().
ArrayList<ColorIndex> view.components.Palette.getColorList ()
Definition at line 68 of file Palette.java.
References view.components.Palette.myColorPalettes.
Image view.components.Palette.getImage (int index)
Definition at line 50 of file Palette.java.
Referenced by view.turtle.TurtleImage.processUpdate().
ArrayList<ImageIndex> view.components.Palette.getImageList ()
Definition at line 64 of file Palette.java.
References view.components.Palette.myImagePalettes.
int view.components.Palette.imageListSize ()
Definition at line 72 of file Palette.java.
void view.components.Palette.updateColor (int index, ColorIndex colx)
Definition at line 37 of file Palette.java.
References view.components.Palette.addColor().
Referenced by view.components.Palette.updateColor().
void view.components.Palette.updateColor (int index, int r, int g, int b)
Definition at line 45 of file Palette.java.
References view.components.Palette.updateColor().
void view.components.Palette.updateImage (int index, ImageIndex imgx)
Definition at line 29 of file Palette.java.
References view.components.Palette.addImage().
Member Data Documentation
ArrayList<ColorIndex> view.components.Palette.myColorPalettes private
Definition at line 10 of file Palette.java.
Referenced by view.components.Palette.getColorList().
ArrayList<ImageIndex> view.components.Palette.myImagePalettes private
Definition at line 9 of file Palette.java.
Referenced by view.components.Palette.getImageList().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/components/Palette.java