slogo_team17: model.TurtleSingle Class Reference
model.TurtleSingle Class Reference
Public Member Functions
TurtleSingle (int id)
void createPen ()
int getID ()
Angle getAngle ()
Coordinates getCoordinates ()
Coordinates getOldCoordinates ()
double addDegree (double degrees)
double moveDistance (double distance)
double setHeading (double degrees)
double setTowards (double x, double y)
void setHidden (boolean b)
void setInactive (boolean b)
void setPenUp (boolean b)
boolean getHidden ()
boolean getInactive ()
boolean getPenUp ()
void addObserver (Observer o)
void removeObserver (Observer o)
void notifyObservers ()
void notifyObservers (Object obj)
double moveToPosition (double x, double y)
void changePen (PenChanger vc)
void change (TurtleSingleChanger tsc)
int getShapeID ()
boolean getStamp ()
void setShapeID (int ID)
void setStamp (boolean b)
int getPenColor ()
boolean equals (TurtleSingle t)
Protected Member Functions
Coordinates distanceToCoordinates (double distance)
Package Attributes
Coordinates myOldCoordinates
boolean isHidden
boolean isInactive
Private Attributes
int ID
Coordinates myCoordinates
Angle myAngle
boolean isPenUp
Pen myPen
int shapeID
boolean isStamp
List< Observer > myObservers
Detailed Description
Definition at line 8 of file TurtleSingle.java.
Constructor & Destructor Documentation
model.TurtleSingle.TurtleSingle (int id)
Definition at line 19 of file TurtleSingle.java.
Member Function Documentation
double model.TurtleSingle.addDegree (double degrees)
Implements model.Turtle.
Definition at line 54 of file TurtleSingle.java.
References model.Angle.addAngleValue(), and model.TurtleSingle.notifyObservers().
Referenced by model.TurtleMultiple.addDegree().
void model.TurtleSingle.addObserver (Observer o)
Implements model.Observable.
Definition at line 128 of file TurtleSingle.java.
Referenced by model.TurtleMultiple.addNewTurtle().
void model.TurtleSingle.change (TurtleSingleChanger tsc)
Definition at line 178 of file TurtleSingle.java.
References model.TurtleSingleChanger.change().
Referenced by model.TurtleSingle.moveDistance().
void model.TurtleSingle.changePen (PenChanger vc)
Implements model.Turtle.
Definition at line 173 of file TurtleSingle.java.
References model.PenChanger.change(), and model.TurtleSingle.notifyObservers().
void model.TurtleSingle.createPen ()
Definition at line 27 of file TurtleSingle.java.
References model.TurtleSingle.notifyObservers().
Referenced by model.TurtleMultiple.addNewTurtle().
Coordinates model.TurtleSingle.distanceToCoordinates (double distance) protected
Definition at line 163 of file TurtleSingle.java.
References model.Angle.getAngleValueInRadians(), and model.Coordinates.scale().
Referenced by model.TurtleSingle.moveDistance().
boolean model.TurtleSingle.equals (TurtleSingle t)
Definition at line 206 of file TurtleSingle.java.
References model.TurtleSingle.getID().
Angle model.TurtleSingle.getAngle ()
Implements model.Turtle.
Definition at line 37 of file TurtleSingle.java.
Referenced by model.TurtleMultiple.getAngle(), and model.TurtleUpdate.TurtleUpdate().
Coordinates model.TurtleSingle.getCoordinates ()
Implements model.Turtle.
Definition at line 44 of file TurtleSingle.java.
Referenced by model.TurtleMultiple.getCoordinates(), model.TurtleSingle.moveToPosition(), and model.TurtleUpdate.TurtleUpdate().
boolean model.TurtleSingle.getHidden ()
Implements model.Turtle.
Definition at line 113 of file TurtleSingle.java.
References model.TurtleSingle.isHidden.
Referenced by model.TurtleMultiple.getHidden(), and model.TurtleUpdate.TurtleUpdate().
int model.TurtleSingle.getID ()
Implements model.Turtle.
Definition at line 32 of file TurtleSingle.java.
References model.TurtleSingle.ID.
Referenced by model.TurtleMultiple.addDegree(), model.TurtleSingle.equals(), model.TurtleMultiple.getID(), model.TurtleMultiple.moveDistance(), model.TurtleMultiple.moveToPosition(), model.TurtleMultiple.setHeading(), model.TurtleMultiple.setTowards(), and model.TurtleUpdate.TurtleUpdate().
boolean model.TurtleSingle.getInactive ()
Implements model.Turtle.
Definition at line 118 of file TurtleSingle.java.
References model.TurtleSingle.isInactive.
Referenced by model.TurtleMultiple.getInactive(), and model.TurtleUpdate.TurtleUpdate().
Coordinates model.TurtleSingle.getOldCoordinates ()
Implements model.Turtle.
Definition at line 49 of file TurtleSingle.java.
Referenced by model.TurtleMultiple.getOldCoordinates(), and model.TurtleUpdate.TurtleUpdate().
int model.TurtleSingle.getPenColor ()
Implements model.Turtle.
Definition at line 202 of file TurtleSingle.java.
References model.Pen.getPenColorIDProperty().
Referenced by model.TurtleMultiple.getPenColor().
boolean model.TurtleSingle.getPenUp ()
Implements model.Turtle.
Definition at line 123 of file TurtleSingle.java.
References model.TurtleSingle.isPenUp.
Referenced by model.TurtleMultiple.getPenUp(), and model.TurtleUpdate.TurtleUpdate().
int model.TurtleSingle.getShapeID ()
Implements model.Turtle.
Definition at line 182 of file TurtleSingle.java.
References model.TurtleSingle.shapeID.
Referenced by model.TurtleMultiple.getShapeID(), and model.TurtleUpdate.TurtleUpdate().
boolean model.TurtleSingle.getStamp ()
Implements model.Turtle.
Definition at line 185 of file TurtleSingle.java.
References model.TurtleSingle.isStamp.
Referenced by model.TurtleMultiple.getStamp(), and model.TurtleUpdate.TurtleUpdate().
double model.TurtleSingle.moveDistance (double distance)
Implements model.Turtle.
Definition at line 62 of file TurtleSingle.java.
References model.Coordinates.addCoordinates(), model.TurtleSingle.change(), model.TurtleSingle.distanceToCoordinates(), and model.TurtleSingle.notifyObservers().
Referenced by model.TurtleMultiple.moveDistance().
double model.TurtleSingle.moveToPosition (double x, double y)
Implements model.Turtle.
Definition at line 154 of file TurtleSingle.java.
References model.Coordinates.addCoordinates(), model.Coordinates.distance(), model.TurtleSingle.getCoordinates(), model.Coordinates.getX(), model.Coordinates.getY(), and model.TurtleSingle.notifyObservers().
Referenced by model.TurtleMultiple.moveToPosition().
void model.TurtleSingle.notifyObservers ()
Implements model.Observable.
Definition at line 138 of file TurtleSingle.java.
Referenced by model.TurtleSingle.addDegree(), model.TurtleMultiple.addNewTurtle(), model.TurtleSingle.changePen(), model.TurtleSingle.createPen(), model.TurtleSingle.moveDistance(), model.TurtleSingle.moveToPosition(), model.TurtleSingle.setHeading(), model.TurtleSingle.setHidden(), model.TurtleSingle.setInactive(), model.TurtleSingle.setPenUp(), model.TurtleSingle.setShapeID(), model.TurtleSingle.setStamp(), and model.TurtleSingle.setTowards().
void model.TurtleSingle.notifyObservers (Object obj)
Definition at line 145 of file TurtleSingle.java.
void model.TurtleSingle.removeObserver (Observer o)
Implements model.Observable.
Definition at line 133 of file TurtleSingle.java.
double model.TurtleSingle.setHeading (double degrees)
Implements model.Turtle.
Definition at line 72 of file TurtleSingle.java.
References model.Angle.getAngleValue(), model.TurtleSingle.notifyObservers(), and model.Angle.setAngleValue().
Referenced by model.TurtleMultiple.setHeading(), and model.TurtleSingle.setTowards().
void model.TurtleSingle.setHidden (boolean b)
Implements model.Turtle.
Definition at line 95 of file TurtleSingle.java.
References model.TurtleSingle.notifyObservers().
void model.TurtleSingle.setInactive (boolean b)
Implements model.Turtle.
Definition at line 101 of file TurtleSingle.java.
References model.TurtleSingle.notifyObservers().
Referenced by parser.commands.AskWith.createNewActiveStack().
void model.TurtleSingle.setPenUp (boolean b)
Implements model.Turtle.
Definition at line 107 of file TurtleSingle.java.
References model.TurtleSingle.notifyObservers().
void model.TurtleSingle.setShapeID (int ID)
Implements model.Turtle.
Definition at line 190 of file TurtleSingle.java.
References model.TurtleSingle.ID, and model.TurtleSingle.notifyObservers().
void model.TurtleSingle.setStamp (boolean b)
Implements model.Turtle.
Definition at line 196 of file TurtleSingle.java.
References model.TurtleSingle.notifyObservers().
double model.TurtleSingle.setTowards (double x, double y)
Implements model.Turtle.
Definition at line 80 of file TurtleSingle.java.
References model.Coordinates.getX(), model.Coordinates.getY(), model.TurtleSingle.notifyObservers(), and model.TurtleSingle.setHeading().
Referenced by model.TurtleMultiple.setTowards().
Member Data Documentation
int model.TurtleSingle.ID private
Definition at line 9 of file TurtleSingle.java.
Referenced by model.TurtleSingle.getID(), and model.TurtleSingle.setShapeID().
boolean model.TurtleSingle.isHidden package
Definition at line 12 of file TurtleSingle.java.
Referenced by model.TurtleSingle.getHidden().
boolean model.TurtleSingle.isInactive package
Definition at line 12 of file TurtleSingle.java.
Referenced by model.TurtleSingle.getInactive().
boolean model.TurtleSingle.isPenUp private
Definition at line 12 of file TurtleSingle.java.
Referenced by model.TurtleSingle.getPenUp().
boolean model.TurtleSingle.isStamp private
Definition at line 14 of file TurtleSingle.java.
Referenced by model.TurtleSingle.getStamp().
Angle model.TurtleSingle.myAngle private
Definition at line 11 of file TurtleSingle.java.
Coordinates model.TurtleSingle.myCoordinates private
Definition at line 10 of file TurtleSingle.java.
List<Observer> model.TurtleSingle.myObservers private
Definition at line 17 of file TurtleSingle.java.
Coordinates model.TurtleSingle.myOldCoordinates package
Definition at line 10 of file TurtleSingle.java.
Pen model.TurtleSingle.myPen private
Definition at line 13 of file TurtleSingle.java.
int model.TurtleSingle.shapeID private
Definition at line 14 of file TurtleSingle.java.
Referenced by model.TurtleSingle.getShapeID().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/TurtleSingle.java