slogo_team17: model.VariableDouble Class Reference
model.VariableDouble Class Reference
Public Member Functions
VariableDouble (String name, double value)
Object getValue ()
Variable clone ()
void setValue (String edit) throws VariableWrongTypeException
Public Member Functions inherited from model.Variable
Variable (String name)
abstract Object getValue ()
abstract void setValue (String edit) throws VariableWrongTypeException
Private Attributes
DoubleProperty myProperty
Additional Inherited Members
Protected Member Functions inherited from model.Variable
StringProperty getStringProperty ()
StringProperty getNameProperty ()
Protected Attributes inherited from model.Variable
StringProperty myDisplayProperty
StringProperty myNameProperty
Detailed Description
Definition at line 9 of file VariableDouble.java.
Constructor & Destructor Documentation
model.VariableDouble.VariableDouble (String name, double value)
Definition at line 12 of file VariableDouble.java.
References model.Variable.myDisplayProperty.
Referenced by model.VariableDouble.clone().
Member Function Documentation
Variable model.VariableDouble.clone ()
Definition at line 37 of file VariableDouble.java.
References model.Variable.getNameProperty(), model.VariableDouble.getValue(), and model.VariableDouble.VariableDouble().
Object model.VariableDouble.getValue ()
Definition at line 32 of file VariableDouble.java.
Referenced by model.VariableDouble.clone().
void model.VariableDouble.setValue (String edit) throws VariableWrongTypeException
Definition at line 42 of file VariableDouble.java.
Member Data Documentation
DoubleProperty model.VariableDouble.myProperty private
Definition at line 10 of file VariableDouble.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/VariableDouble.java