slogo_team17: view.components.SLogoWorkspace Class Reference
view.components.SLogoWorkspace Class Reference
Public Member Functions
SLogoWorkspace (int id)
SLogoWorkspace (String title, int id)
void startDebugger ()
void stopDebugger ()
void runDebugger ()
void setTitle (String title)
String getTitle ()
int getWorkspaceID ()
void setLanguage (String language)
String getLanguage ()
TurtleWindow getTurtleWindow ()
VariablesWindow getVariablesWindow ()
CommandsHistoryWindow getCommandHistoryWindow ()
UserDefinedCommandsWindow getUDCommandsWindow ()
Private Member Functions
void addToolbar ()
void addTurtleWindow ()
void addListWindows ()
void initLists ()
void addCommandPortWindow ()
Private Attributes
BorderPane myBorderPane
Toolbar myToolbar
TurtleWindow myTurtleWindow
CommandPort myCommandPort
DebuggerPort myDebugPort
UserDefinedCommandsWindow myUDCommandsWindow
VariablesWindow myVariablesWindow
CommandsHistoryWindow myCommandHistWindow
VBox myListWindows
HBox myUDListWindows
String myTitle
String myLanguage
int myID
Static Private Attributes
static final String DEFAULT_LANGUAGE = "English"
static final Color BACKGROUND_COLOR = Color.LIGHTGREY
Detailed Description
Definition at line 17 of file SLogoWorkspace.java.
Constructor & Destructor Documentation
view.components.SLogoWorkspace.SLogoWorkspace (int id)
Definition at line 40 of file SLogoWorkspace.java.
view.components.SLogoWorkspace.SLogoWorkspace (String title, int id)
Definition at line 45 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.addCommandPortWindow(), view.components.SLogoWorkspace.addListWindows(), view.components.SLogoWorkspace.addToolbar(), view.components.SLogoWorkspace.addTurtleWindow(), and view.components.SLogoWorkspace.DEFAULT_LANGUAGE.
Member Function Documentation
void view.components.SLogoWorkspace.addCommandPortWindow () private
Definition at line 103 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.SLogoWorkspace().
void view.components.SLogoWorkspace.addListWindows () private
Definition at line 80 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.initLists().
Referenced by view.components.SLogoWorkspace.SLogoWorkspace().
void view.components.SLogoWorkspace.addToolbar () private
Definition at line 66 of file SLogoWorkspace.java.
References view.toolbar.Toolbar.setTurtleWindow().
Referenced by view.components.SLogoWorkspace.SLogoWorkspace().
void view.components.SLogoWorkspace.addTurtleWindow () private
Definition at line 72 of file SLogoWorkspace.java.
References view.Main.SIZE.
Referenced by view.components.SLogoWorkspace.SLogoWorkspace().
CommandsHistoryWindow view.components.SLogoWorkspace.getCommandHistoryWindow ()
Definition at line 154 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.myCommandHistWindow.
String view.components.SLogoWorkspace.getLanguage ()
Definition at line 142 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.myLanguage.
String view.components.SLogoWorkspace.getTitle ()
Definition at line 130 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.myTitle.
TurtleWindow view.components.SLogoWorkspace.getTurtleWindow ()
Definition at line 146 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.myTurtleWindow.
UserDefinedCommandsWindow view.components.SLogoWorkspace.getUDCommandsWindow ()
Definition at line 158 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.myUDCommandsWindow.
VariablesWindow view.components.SLogoWorkspace.getVariablesWindow ()
Definition at line 150 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.myVariablesWindow.
int view.components.SLogoWorkspace.getWorkspaceID ()
Definition at line 134 of file SLogoWorkspace.java.
References view.components.SLogoWorkspace.myID.
void view.components.SLogoWorkspace.initLists () private
Definition at line 94 of file SLogoWorkspace.java.
References view.Main.SIZE.
Referenced by view.components.SLogoWorkspace.addListWindows().
void view.components.SLogoWorkspace.runDebugger ()
Definition at line 121 of file SLogoWorkspace.java.
References view.components.TurtleWindow.stepDebug().
Referenced by view.View.runDebugger().
void view.components.SLogoWorkspace.setLanguage (String language)
Definition at line 138 of file SLogoWorkspace.java.
void view.components.SLogoWorkspace.setTitle (String title)
Definition at line 125 of file SLogoWorkspace.java.
Referenced by view.View.setTabTitle().
void view.components.SLogoWorkspace.startDebugger ()
Definition at line 109 of file SLogoWorkspace.java.
References view.components.TurtleWindow.enterDebugMode().
Referenced by view.View.addDebuger().
void view.components.SLogoWorkspace.stopDebugger ()
Definition at line 115 of file SLogoWorkspace.java.
References view.components.TurtleWindow.exitDebugMode().
Referenced by view.View.removeDebuger().
Member Data Documentation
final Color view.components.SLogoWorkspace.BACKGROUND_COLOR = Color.LIGHTGREY static private
Definition at line 38 of file SLogoWorkspace.java.
final String view.components.SLogoWorkspace.DEFAULT_LANGUAGE = "English" static private
Definition at line 37 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.SLogoWorkspace().
BorderPane view.components.SLogoWorkspace.myBorderPane private
Definition at line 19 of file SLogoWorkspace.java.
CommandsHistoryWindow view.components.SLogoWorkspace.myCommandHistWindow private
Definition at line 28 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.getCommandHistoryWindow().
CommandPort view.components.SLogoWorkspace.myCommandPort private
Definition at line 23 of file SLogoWorkspace.java.
DebuggerPort view.components.SLogoWorkspace.myDebugPort private
Definition at line 24 of file SLogoWorkspace.java.
int view.components.SLogoWorkspace.myID private
Definition at line 35 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.getWorkspaceID().
String view.components.SLogoWorkspace.myLanguage private
Definition at line 33 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.getLanguage().
VBox view.components.SLogoWorkspace.myListWindows private
Definition at line 29 of file SLogoWorkspace.java.
String view.components.SLogoWorkspace.myTitle private
Definition at line 32 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.getTitle().
Toolbar view.components.SLogoWorkspace.myToolbar private
Definition at line 21 of file SLogoWorkspace.java.
TurtleWindow view.components.SLogoWorkspace.myTurtleWindow private
Definition at line 22 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.getTurtleWindow().
UserDefinedCommandsWindow view.components.SLogoWorkspace.myUDCommandsWindow private
Definition at line 26 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.getUDCommandsWindow().
HBox view.components.SLogoWorkspace.myUDListWindows private
Definition at line 30 of file SLogoWorkspace.java.
VariablesWindow view.components.SLogoWorkspace.myVariablesWindow private
Definition at line 27 of file SLogoWorkspace.java.
Referenced by view.components.SLogoWorkspace.getVariablesWindow().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/components/SLogoWorkspace.java