slogo_team17: model.TurtleMultiple Class Reference
model.TurtleMultiple Class Reference
Public Member Functions
TurtleMultiple ()
void addNewTurtle (int turtleID)
int numTurtles ()
void deactiveAll ()
TurtleSingle getTurtleSingle (int turtleID) throws TurtleNotFoundException
void addObserver (Observer o)
void removeObserver (Observer o)
void notifyObservers ()
Angle getAngle ()
Coordinates getCoordinates ()
Coordinates getOldCoordinates ()
double addDegree (double degree)
double moveDistance (double distance)
double setHeading (double degrees)
double setTowards (double x, double y)
double moveToPosition (double x, double y)
void setHidden (boolean b)
void setInactive (boolean b)
void setPenUp (boolean b)
boolean getHidden ()
boolean getInactive ()
boolean getPenUp ()
int getShapeID ()
boolean getStamp ()
List< Integer > activeTurtleIDs ()
int getID ()
void changePen (PenChanger pc)
void change (TurtleSingleChanger tsc)
void setStamp (boolean b)
void setShapeID (int ID)
int getPenColor ()
Private Member Functions
void setLastTurtle (TurtleSingle t)
Stream< TurtleSingle > getStream ()
Private Attributes
Map< Integer, TurtleSingle > myTurtleMap
TurtleSingle lastActingTurtle
boolean stampsOut
Detailed Description
Has similar behavior to TurtleSingle following the composite pattern.
Definition at line 19 of file TurtleMultiple.java.
Constructor & Destructor Documentation
model.TurtleMultiple.TurtleMultiple ()
Definition at line 24 of file TurtleMultiple.java.
References model.TurtleMultiple.addNewTurtle().
Member Function Documentation
List<Integer> model.TurtleMultiple.activeTurtleIDs ()
Definition at line 160 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
Referenced by parser.commands.Ask.createOldActiveStack().
double model.TurtleMultiple.addDegree (double degree)
Implements model.Turtle.
Definition at line 87 of file TurtleMultiple.java.
References model.TurtleSingle.addDegree(), model.TurtleSingle.getID(), and model.TurtleMultiple.getStream().
void model.TurtleMultiple.addNewTurtle (int turtleID)
Definition at line 29 of file TurtleMultiple.java.
References model.TurtleSingle.addObserver(), model.TurtleSingle.createPen(), view.View.getInstance(), view.View.getTurtleWindow(), model.TurtleSingle.notifyObservers(), and model.TurtleMultiple.setLastTurtle().
Referenced by model.TurtleMultiple.TurtleMultiple().
void model.TurtleMultiple.addObserver (Observer o)
Implements model.Observable.
Definition at line 57 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
void model.TurtleMultiple.change (TurtleSingleChanger tsc)
Definition at line 176 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
void model.TurtleMultiple.changePen (PenChanger pc)
Implements model.Turtle.
Definition at line 172 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
void model.TurtleMultiple.deactiveAll ()
Definition at line 42 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
Referenced by parser.commands.AskWith.createNewActiveStack(), and parser.commands.Tell.execute().
Angle model.TurtleMultiple.getAngle ()
Implements model.Turtle.
Definition at line 70 of file TurtleMultiple.java.
References model.TurtleSingle.getAngle().
Referenced by parser.commands.ParserTest.testParse().
Coordinates model.TurtleMultiple.getCoordinates ()
Implements model.Turtle.
Definition at line 75 of file TurtleMultiple.java.
References model.TurtleSingle.getCoordinates().
Referenced by parser.commands.ParserTest.testParse().
boolean model.TurtleMultiple.getHidden ()
Implements model.Turtle.
Definition at line 132 of file TurtleMultiple.java.
References model.TurtleSingle.getHidden().
int model.TurtleMultiple.getID ()
Implements model.Turtle.
Definition at line 164 of file TurtleMultiple.java.
References model.TurtleSingle.getID().
boolean model.TurtleMultiple.getInactive ()
Implements model.Turtle.
Definition at line 137 of file TurtleMultiple.java.
References model.TurtleSingle.getInactive().
Coordinates model.TurtleMultiple.getOldCoordinates ()
Implements model.Turtle.
Definition at line 80 of file TurtleMultiple.java.
References model.TurtleSingle.getOldCoordinates().
int model.TurtleMultiple.getPenColor ()
Implements model.Turtle.
Definition at line 191 of file TurtleMultiple.java.
References model.TurtleSingle.getPenColor().
boolean model.TurtleMultiple.getPenUp ()
Implements model.Turtle.
Definition at line 142 of file TurtleMultiple.java.
References model.TurtleSingle.getPenUp().
int model.TurtleMultiple.getShapeID ()
Implements model.Turtle.
Definition at line 147 of file TurtleMultiple.java.
References model.TurtleSingle.getShapeID().
boolean model.TurtleMultiple.getStamp ()
Implements model.Turtle.
Definition at line 152 of file TurtleMultiple.java.
References model.TurtleSingle.getStamp().
Stream<TurtleSingle> model.TurtleMultiple.getStream () private
Definition at line 195 of file TurtleMultiple.java.
References model.TurtleMultiple.setLastTurtle().
Referenced by model.TurtleMultiple.activeTurtleIDs(), model.TurtleMultiple.addDegree(), model.TurtleMultiple.addObserver(), model.TurtleMultiple.change(), model.TurtleMultiple.changePen(), model.TurtleMultiple.deactiveAll(), model.TurtleMultiple.moveDistance(), model.TurtleMultiple.moveToPosition(), model.TurtleMultiple.removeObserver(), model.TurtleMultiple.setHeading(), model.TurtleMultiple.setHidden(), model.TurtleMultiple.setInactive(), model.TurtleMultiple.setPenUp(), model.TurtleMultiple.setShapeID(), model.TurtleMultiple.setStamp(), and model.TurtleMultiple.setTowards().
TurtleSingle model.TurtleMultiple.getTurtleSingle (int turtleID) throws TurtleNotFoundException
Definition at line 46 of file TurtleMultiple.java.
References model.TurtleMultiple.setLastTurtle().
Referenced by parser.commands.AskWith.createNewActiveStack().
double model.TurtleMultiple.moveDistance (double distance)
Implements model.Turtle.
Definition at line 93 of file TurtleMultiple.java.
References model.TurtleSingle.getID(), model.TurtleMultiple.getStream(), and model.TurtleSingle.moveDistance().
double model.TurtleMultiple.moveToPosition (double x, double y)
Implements model.Turtle.
Definition at line 111 of file TurtleMultiple.java.
References model.TurtleSingle.getID(), model.TurtleMultiple.getStream(), and model.TurtleSingle.moveToPosition().
void model.TurtleMultiple.notifyObservers ()
Implements model.Observable.
Definition at line 67 of file TurtleMultiple.java.
int model.TurtleMultiple.numTurtles ()
Definition at line 38 of file TurtleMultiple.java.
Referenced by parser.commands.AskWith.createNewActiveStack().
void model.TurtleMultiple.removeObserver (Observer o)
Implements model.Observable.
Definition at line 62 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
double model.TurtleMultiple.setHeading (double degrees)
Implements model.Turtle.
Definition at line 99 of file TurtleMultiple.java.
References model.TurtleSingle.getID(), model.TurtleMultiple.getStream(), and model.TurtleSingle.setHeading().
void model.TurtleMultiple.setHidden (boolean b)
Implements model.Turtle.
Definition at line 117 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
void model.TurtleMultiple.setInactive (boolean b)
Implements model.Turtle.
Definition at line 122 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
void model.TurtleMultiple.setLastTurtle (TurtleSingle t) private
Definition at line 168 of file TurtleMultiple.java.
Referenced by model.TurtleMultiple.addNewTurtle(), model.TurtleMultiple.getStream(), and model.TurtleMultiple.getTurtleSingle().
void model.TurtleMultiple.setPenUp (boolean b)
Implements model.Turtle.
Definition at line 127 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
Referenced by parser.commands.PenDown.execute(), and parser.commands.PenUp.execute().
void model.TurtleMultiple.setShapeID (int ID)
Implements model.Turtle.
Definition at line 186 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
void model.TurtleMultiple.setStamp (boolean b)
Implements model.Turtle.
Definition at line 181 of file TurtleMultiple.java.
References model.TurtleMultiple.getStream().
double model.TurtleMultiple.setTowards (double x, double y)
Implements model.Turtle.
Definition at line 105 of file TurtleMultiple.java.
References model.TurtleSingle.getID(), model.TurtleMultiple.getStream(), and model.TurtleSingle.setTowards().
Member Data Documentation
TurtleSingle model.TurtleMultiple.lastActingTurtle private
Definition at line 21 of file TurtleMultiple.java.
Map<Integer,TurtleSingle> model.TurtleMultiple.myTurtleMap private
Definition at line 20 of file TurtleMultiple.java.
boolean model.TurtleMultiple.stampsOut private
Definition at line 22 of file TurtleMultiple.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/TurtleMultiple.java