slogo_team17: model.TurtleUpdate Class Reference
model.TurtleUpdate Class Reference
Public Member Functions
TurtleUpdate (TurtleSingle t)
int getTurtleID ()
Angle getTurtleAngle ()
Coordinates getTurtleNewCoordinates ()
Coordinates getTurtleOldCoordinates ()
boolean isTurtleHidden ()
boolean isTurtleInactive ()
boolean isTurtlePenUp ()
boolean isTurtleClear ()
int compareTo (Object arg0)
int getShapeID ()
boolean isStamp ()
Package Attributes
int shapeID
Coordinates turtleNewCoordinates
boolean turtleActive
boolean turtlePenUp
boolean turtleClear
boolean turtleStamp
Private Attributes
int turtleID
Angle turtleAngle
Coordinates turtleOldCoordinates
boolean turtleHidden
Detailed Description
A data object that captures a snapshot of the turtle's state. Is sent to observers any time the turtle changes.
Definition at line 7 of file TurtleUpdate.java.
Constructor & Destructor Documentation
model.TurtleUpdate.TurtleUpdate (TurtleSingle t)
Definition at line 15 of file TurtleUpdate.java.
References model.TurtleSingle.getAngle(), model.TurtleSingle.getCoordinates(), model.TurtleSingle.getHidden(), model.TurtleSingle.getID(), model.TurtleSingle.getInactive(), model.TurtleSingle.getOldCoordinates(), model.TurtleSingle.getPenUp(), model.TurtleSingle.getShapeID(), and model.TurtleSingle.getStamp().
Member Function Documentation
int model.TurtleUpdate.compareTo (Object arg0)
Definition at line 54 of file TurtleUpdate.java.
int model.TurtleUpdate.getShapeID ()
Definition at line 57 of file TurtleUpdate.java.
References model.TurtleUpdate.shapeID.
Referenced by view.turtle.TurtleImage.processUpdate().
Angle model.TurtleUpdate.getTurtleAngle ()
Definition at line 30 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleAngle.
Referenced by view.turtle.TurtleImage.processUpdate().
int model.TurtleUpdate.getTurtleID ()
Definition at line 27 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleID.
Referenced by view.components.TurtleWindow.update().
Coordinates model.TurtleUpdate.getTurtleNewCoordinates ()
Definition at line 33 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleNewCoordinates.
Referenced by view.turtle.TurtleImage.processUpdate().
Coordinates model.TurtleUpdate.getTurtleOldCoordinates ()
Definition at line 36 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleOldCoordinates.
Referenced by view.turtle.TurtleImage.processUpdate().
boolean model.TurtleUpdate.isStamp ()
Definition at line 60 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleStamp.
Referenced by view.turtle.TurtleImage.processUpdate().
boolean model.TurtleUpdate.isTurtleClear ()
Definition at line 49 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleClear.
Referenced by view.turtle.TurtleImage.processUpdate().
boolean model.TurtleUpdate.isTurtleHidden ()
Definition at line 39 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleHidden.
Referenced by view.turtle.TurtleImage.processUpdate().
boolean model.TurtleUpdate.isTurtleInactive ()
Definition at line 42 of file TurtleUpdate.java.
References model.TurtleUpdate.turtleActive.
Referenced by view.turtle.TurtleImage.processUpdate().
boolean model.TurtleUpdate.isTurtlePenUp ()
Definition at line 45 of file TurtleUpdate.java.
References model.TurtleUpdate.turtlePenUp.
Referenced by view.turtle.TurtleImage.processUpdate().
Member Data Documentation
int model.TurtleUpdate.shapeID package
Definition at line 8 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.getShapeID().
boolean model.TurtleUpdate.turtleActive package
Definition at line 11 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.isTurtleInactive().
Angle model.TurtleUpdate.turtleAngle private
Definition at line 9 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.getTurtleAngle().
boolean model.TurtleUpdate.turtleClear package
Definition at line 11 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.isTurtleClear().
boolean model.TurtleUpdate.turtleHidden private
Definition at line 11 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.isTurtleHidden().
int model.TurtleUpdate.turtleID private
Definition at line 8 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.getTurtleID().
Coordinates model.TurtleUpdate.turtleNewCoordinates package
Definition at line 10 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.getTurtleNewCoordinates().
Coordinates model.TurtleUpdate.turtleOldCoordinates private
Definition at line 10 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.getTurtleOldCoordinates().
boolean model.TurtleUpdate.turtlePenUp package
Definition at line 11 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.isTurtlePenUp().
boolean model.TurtleUpdate.turtleStamp package
Definition at line 11 of file TurtleUpdate.java.
Referenced by model.TurtleUpdate.isStamp().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/TurtleUpdate.java