slogo_team17: view.toolbar.TurtleImageToolbarItem Class Reference
view.toolbar.TurtleImageToolbarItem Class Reference
Public Member Functions
void changeTurtleProperties (int turtleID)
Public Member Functions inherited from view.toolbar.TurtleSpecificToolbarItem
abstract void changeTurtleProperties (int turtleID)
Protected Member Functions
TurtleImageToolbarItem (String label, Toolbar tb)
Node createNode ()
Protected Member Functions inherited from view.toolbar.TurtleSpecificToolbarItem
TurtleSpecificToolbarItem (String label, Toolbar tb)
void getAndModifyTurtles ()
Protected Member Functions inherited from view.toolbar.ToolbarItem
ToolbarItem (String label, Toolbar container)
void setLabel (String label)
abstract Node createNode ()
Private Member Functions
FileChooser makeImageChooser ()
Private Attributes
File myFile
Static Private Attributes
static final String CHOOSE = "Choose"
Additional Inherited Members
Protected Attributes inherited from view.toolbar.ToolbarItem
Toolbar myToolbar
Node myNode
Label myLabel
Static Protected Attributes inherited from view.toolbar.TurtleSpecificToolbarItem
static final String TURTLE_PROMPT
Package Attributes inherited from view.toolbar.TurtleSpecificToolbarItem
List< Integer > selectedTurtles
Detailed Description
Toolbar Item to change turtle image.
Author
lien
Definition at line 17 of file TurtleImageToolbarItem.java.
Constructor & Destructor Documentation
view.toolbar.TurtleImageToolbarItem.TurtleImageToolbarItem (String label, Toolbar tb) protected
Definition at line 23 of file TurtleImageToolbarItem.java.
Member Function Documentation
void view.toolbar.TurtleImageToolbarItem.changeTurtleProperties (int turtleID)
Definition at line 28 of file TurtleImageToolbarItem.java.
References view.components.TurtleWindow.changeTurtleImage(), view.toolbar.Toolbar.getTurtleWindow(), and view.toolbar.ToolbarItem.myToolbar.
Node view.toolbar.TurtleImageToolbarItem.createNode () protected
Definition at line 34 of file TurtleImageToolbarItem.java.
References view.toolbar.TurtleSpecificToolbarItem.getAndModifyTurtles(), and view.toolbar.TurtleImageToolbarItem.makeImageChooser().
FileChooser view.toolbar.TurtleImageToolbarItem.makeImageChooser () private
Definition at line 46 of file TurtleImageToolbarItem.java.
Referenced by view.toolbar.TurtleImageToolbarItem.createNode().
Member Data Documentation
final String view.toolbar.TurtleImageToolbarItem.CHOOSE = "Choose" static private
Definition at line 20 of file TurtleImageToolbarItem.java.
File view.toolbar.TurtleImageToolbarItem.myFile private
Definition at line 21 of file TurtleImageToolbarItem.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/toolbar/TurtleImageToolbarItem.java