slogo_team17: parser.nodes.ListNode Class Reference
parser.nodes.ListNode Class Reference
Public Member Functions
ListNode (Stack< SyntaxNode > input)
SyntaxNode getNode (int index)
double execute (State myState) throws BadArgumentException
int getSize ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract double execute (State myState) throws BadArgumentException
Protected Member Functions
double executeNodes (State myState) throws BadArgumentException
Protected Attributes
List< SyntaxNode > myList = new ArrayList<SyntaxNode>()
Detailed Description
Definition at line 10 of file ListNode.java.
Constructor & Destructor Documentation
parser.nodes.ListNode.ListNode (Stack< SyntaxNode > input)
Definition at line 14 of file ListNode.java.
Member Function Documentation
double parser.nodes.ListNode.execute (State myState) throws BadArgumentException
Definition at line 28 of file ListNode.java.
References parser.nodes.ListNode.executeNodes().
Referenced by parser.commands.ToInstance.execute(), and parser.nodes.ListNode.executeNodes().
double parser.nodes.ListNode.executeNodes (State myState) throws BadArgumentException protected
Definition at line 35 of file ListNode.java.
References parser.nodes.ListNode.execute().
Referenced by parser.nodes.CommandRoot.execute(), and parser.nodes.ListNode.execute().
SyntaxNode parser.nodes.ListNode.getNode (int index)
Definition at line 23 of file ListNode.java.
Referenced by parser.commands.Ask.createNewActiveStack(), parser.commands.DoTimes.execute(), parser.commands.For.execute(), parser.commands.Tell.execute(), parser.commands.ToInstance.execute(), and parser.commands.LoopingNode.LoopingNode().
int parser.nodes.ListNode.getSize ()
Definition at line 43 of file ListNode.java.
Referenced by parser.commands.Ask.createNewActiveStack(), parser.commands.DoTimes.DoTimes(), parser.commands.Tell.execute(), parser.commands.ToInstance.execute(), parser.commands.For.For(), parser.nodes.GroupNode.GroupNode(), parser.commands.ToInstance.ToInstance(), and parser.nodes.UnlimitedNode.UnlimitedNode().
Member Data Documentation
List<SyntaxNode> parser.nodes.ListNode.myList = new ArrayList<SyntaxNode>() protected
Definition at line 12 of file ListNode.java.
Referenced by parser.nodes.GroupNode.backPop(), parser.nodes.CommandRoot.getChildren(), and parser.nodes.GroupNode.GroupNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/parser/nodes/ListNode.java