slogo_team17: parser.parser.Parser Class Reference
parser.parser.Parser Class Reference
Public Member Functions
void setActiveState (State s)
CommandRoot parse (String command) throws CommandNameNotFoundException, SyntaxErrorWrongFormat
Private Attributes
State myActiveState
Detailed Description
Definition at line 11 of file Parser.java.
Member Function Documentation
CommandRoot parser.parser.Parser.parse (String command) throws CommandNameNotFoundException, SyntaxErrorWrongFormat
Definition at line 18 of file Parser.java.
References parser.parser.CommandFactory.createCommand(), parser.parser.CommandFactory.getInstance(), parser.parser.ToFactory.getInstance(), parser.parser.Regex.getInstance(), and parser.parser.Regex.getType().
Referenced by model.Model.parse(), and parser.commands.ParserTest.testParse().
void parser.parser.Parser.setActiveState (State s)
Definition at line 14 of file Parser.java.
Referenced by model.Model.setState(), and parser.commands.ParserTest.testParse().
Member Data Documentation
State parser.parser.Parser.myActiveState private
Definition at line 12 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/parser/parser/Parser.java