slogo_team17: model.VariablesCollection Class Reference
model.VariablesCollection Class Reference
Public Member Functions
VariablesCollection ()
boolean containsVariable (String varName)
Object getVariableValue (String varName)
void addVariable (String varName, String varValue) throws VariableCreationException, VariableCreationInvalidValueException
void waitScopeVariable (String varName)
void restoreScope ()
VariablesCollectionUpdate produceUpdate ()
void notifyObservers ()
void addObserver (Observer o)
void removeObserver (Observer o)
void enterScope ()
void exitScope ()
String saveState ()
Private Member Functions
Variable findVariable (String varName) throws VariableNotFoundException
Private Attributes
List< Variable > myVariableList
List< Variable > waitingVariableList
List< Observer > myObserverList
Detailed Description
Definition at line 15 of file VariablesCollection.java.
Constructor & Destructor Documentation
model.VariablesCollection.VariablesCollection ()
Definition at line 20 of file VariablesCollection.java.
Member Function Documentation
void model.VariablesCollection.addObserver (Observer o)
Implements model.IVariablesCollection.
Definition at line 119 of file VariablesCollection.java.
void model.VariablesCollection.addVariable (String varName, String varValue) throws VariableCreationException, VariableCreationInvalidValueException
Implements model.IVariablesCollection.
Definition at line 57 of file VariablesCollection.java.
References model.VariableFactory.createVariable(), model.VariablesCollection.findVariable(), model.VariablesCollection.notifyObservers(), and model.Variable.setValue().
Referenced by model.VariablesCollection.getVariableValue().
boolean model.VariablesCollection.containsVariable (String varName)
Definition at line 27 of file VariablesCollection.java.
void model.VariablesCollection.enterScope ()
Implements model.IVariablesCollection.
Definition at line 129 of file VariablesCollection.java.
void model.VariablesCollection.exitScope ()
Implements model.IVariablesCollection.
Definition at line 134 of file VariablesCollection.java.
Variable model.VariablesCollection.findVariable (String varName) throws VariableNotFoundException private
Definition at line 89 of file VariablesCollection.java.
Referenced by model.VariablesCollection.addVariable(), model.VariablesCollection.getVariableValue(), and model.VariablesCollection.waitScopeVariable().
Object model.VariablesCollection.getVariableValue (String varName)
Implements model.IVariablesCollection.
Definition at line 40 of file VariablesCollection.java.
References model.VariablesCollection.addVariable(), model.VariablesCollection.findVariable(), and model.Variable.getValue().
void model.VariablesCollection.notifyObservers ()
Implements model.IVariablesCollection.
Definition at line 111 of file VariablesCollection.java.
References model.VariablesCollection.produceUpdate().
Referenced by model.VariablesCollection.addVariable().
VariablesCollectionUpdate model.VariablesCollection.produceUpdate ()
Definition at line 97 of file VariablesCollection.java.
Referenced by model.VariablesCollection.notifyObservers().
void model.VariablesCollection.removeObserver (Observer o)
Implements model.IVariablesCollection.
Definition at line 124 of file VariablesCollection.java.
void model.VariablesCollection.restoreScope ()
Definition at line 82 of file VariablesCollection.java.
String model.VariablesCollection.saveState ()
Concatenates a String that contains all the necessary variable declarations to recreate the variable collection, for the purpose of saving.
Implements model.IVariablesCollection.
Definition at line 139 of file VariablesCollection.java.
References parser.parser.Regex.getCommandString(), and parser.parser.Regex.getInstance().
void model.VariablesCollection.waitScopeVariable (String varName)
Definition at line 73 of file VariablesCollection.java.
References model.VariablesCollection.findVariable().
Member Data Documentation
List<Observer> model.VariablesCollection.myObserverList private
Definition at line 18 of file VariablesCollection.java.
List<Variable> model.VariablesCollection.myVariableList private
Definition at line 16 of file VariablesCollection.java.
List<Variable> model.VariablesCollection.waitingVariableList private
Definition at line 17 of file VariablesCollection.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/VariablesCollection.java