slogo_team17: parser.nodes.CommandRoot Class Reference
parser.nodes.CommandRoot Class Reference
Public Member Functions
CommandRoot (String s, Stack< SyntaxNode > input)
String toString ()
List< SyntaxNode > getChildren ()
double execute (State myState) throws BadArgumentException
Public Member Functions inherited from parser.nodes.ListNode
ListNode (Stack< SyntaxNode > input)
SyntaxNode getNode (int index)
double execute (State myState) throws BadArgumentException
int getSize ()
Public Member Functions inherited from parser.nodes.SyntaxNode
abstract double execute (State myState) throws BadArgumentException
Private Attributes
String myString
Additional Inherited Members
Protected Member Functions inherited from parser.nodes.ListNode
double executeNodes (State myState) throws BadArgumentException
Protected Attributes inherited from parser.nodes.ListNode
List< SyntaxNode > myList = new ArrayList<SyntaxNode>()
Detailed Description
Definition at line 9 of file CommandRoot.java.
Constructor & Destructor Documentation
parser.nodes.CommandRoot.CommandRoot (String s, Stack< SyntaxNode > input)
Definition at line 12 of file CommandRoot.java.
Member Function Documentation
double parser.nodes.CommandRoot.execute (State myState) throws BadArgumentException
Definition at line 25 of file CommandRoot.java.
References parser.nodes.ListNode.executeNodes().
Referenced by model.Model.parse(), and parser.commands.ParserTest.testParse().
List<SyntaxNode> parser.nodes.CommandRoot.getChildren ()
Definition at line 20 of file CommandRoot.java.
References parser.nodes.ListNode.myList.
String parser.nodes.CommandRoot.toString ()
Definition at line 16 of file CommandRoot.java.
Member Data Documentation
String parser.nodes.CommandRoot.myString private
Definition at line 10 of file CommandRoot.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/parser/nodes/CommandRoot.java