slogo_team17: view.components.SLogoMenuBar Class Reference
view.components.SLogoMenuBar Class Reference
Public Member Functions
SLogoMenuBar (View view)
Static Public Attributes
static final String FILE = "File"
static final String NEW_WORKSPACE = "New workspace"
static final String LOAD_LIBRARY = "Load commands library"
static final String SAVE_LIBRARY = "Save commands library"
static final String PREFERENCES = "Settings"
static final String LANGUAGE = "Change language"
static final String LOAD_WORKSPACE = "Load preferences"
static final String SAVE_WORKSPACE = "Save preferences"
static final String HELP = "Help"
static final String OPEN_HELP = "Open Help"
static final String ABOUT = "About"
Private Member Functions
MenuItem makeMenuItem (String label, EventHandler< ActionEvent > event)
void makeFileMenu ()
void makePreferencesMenu ()
void makeHelpMenu ()
Private Attributes
View myView
Static Private Attributes
static final Color BAR_COLOR = Color.BLACK
Detailed Description
MenuBar for the SLogo program.
Author
lien
Definition at line 21 of file SLogoMenuBar.java.
Constructor & Destructor Documentation
view.components.SLogoMenuBar.SLogoMenuBar (View view)
Definition at line 46 of file SLogoMenuBar.java.
References view.components.SLogoMenuBar.makeFileMenu(), view.components.SLogoMenuBar.makeHelpMenu(), and view.components.SLogoMenuBar.makePreferencesMenu().
Member Function Documentation
void view.components.SLogoMenuBar.makeFileMenu () private
Definition at line 65 of file SLogoMenuBar.java.
References view.View.addNewTab(), and view.components.SLogoMenuBar.makeMenuItem().
Referenced by view.components.SLogoMenuBar.SLogoMenuBar().
void view.components.SLogoMenuBar.makeHelpMenu () private
Definition at line 117 of file SLogoMenuBar.java.
References view.View.showHelp().
Referenced by view.components.SLogoMenuBar.SLogoMenuBar().
MenuItem view.components.SLogoMenuBar.makeMenuItem (String label, EventHandler< ActionEvent > event) private
Definition at line 59 of file SLogoMenuBar.java.
Referenced by view.components.SLogoMenuBar.makeFileMenu().
void view.components.SLogoMenuBar.makePreferencesMenu () private
Definition at line 84 of file SLogoMenuBar.java.
References view.components.TurtleWindow.changeBackground(), view.components.WorkspaceFile.getColor(), view.components.WorkspaceFile.getTitle(), view.View.getTurtleWindow(), view.components.WorkspaceLoader.loadWorkspace(), view.View.setTabTitle(), and view.View.showAndChangeLanguage().
Referenced by view.components.SLogoMenuBar.SLogoMenuBar().
Member Data Documentation
final String view.components.SLogoMenuBar.ABOUT = "About" static
Definition at line 41 of file SLogoMenuBar.java.
final Color view.components.SLogoMenuBar.BAR_COLOR = Color.BLACK static private
Definition at line 44 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.FILE = "File" static
Definition at line 27 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.HELP = "Help" static
Definition at line 39 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.LANGUAGE = "Change language" static
Definition at line 34 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.LOAD_LIBRARY = "Load commands library" static
Definition at line 29 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.LOAD_WORKSPACE = "Load preferences" static
Definition at line 35 of file SLogoMenuBar.java.
View view.components.SLogoMenuBar.myView private
Definition at line 23 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.NEW_WORKSPACE = "New workspace" static
Definition at line 28 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.OPEN_HELP = "Open Help" static
Definition at line 40 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.PREFERENCES = "Settings" static
Definition at line 33 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.SAVE_LIBRARY = "Save commands library" static
Definition at line 30 of file SLogoMenuBar.java.
final String view.components.SLogoMenuBar.SAVE_WORKSPACE = "Save preferences" static
Definition at line 36 of file SLogoMenuBar.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/components/SLogoMenuBar.java