slogo_team17: parser.parser.Regex Class Reference
parser.parser.Regex Class Reference
Public Member Functions
void changeLanguage (String language)
GeneralType getType (String s)
String getCommandType (String s) throws CommandNameNotFoundException
String getCommandString (String commandName) throws CommandNameNotFoundException
Static Public Member Functions
static Regex getInstance ()
Package Attributes
String languageFileString
List< Entry< String, Pattern > > generalPatterns = new ArrayList<>()
List< Entry< String, Pattern > > commandPatterns = new ArrayList<>()
Private Member Functions
Regex ()
boolean match (String input, Pattern regex)
List< Entry< String, Pattern > > makePatterns (String syntax)
Static Private Attributes
static Regex instance
Detailed Description
Definition at line 15 of file Regex.java.
Constructor & Destructor Documentation
parser.parser.Regex.Regex () private
Definition at line 22 of file Regex.java.
References parser.parser.Regex.makePatterns().
Referenced by parser.parser.Regex.getInstance().
Member Function Documentation
void parser.parser.Regex.changeLanguage (String language)
Given file path, will clear the current language patterns and load the new ones from the file.
Definition at line 38 of file Regex.java.
References view.components.LanguageController.getCommandLanguagesFilePath(), and parser.parser.Regex.makePatterns().
Referenced by view.View.showAndChangeLanguage(), and view.View.tabChangeUpdate().
String parser.parser.Regex.getCommandString (String commandName) throws CommandNameNotFoundException
If given the class name of a command, like "MakeVariable", will return a string of the current language's command string (eg. "make" if the language is english).
Definition at line 76 of file Regex.java.
Referenced by model.VariablesCollection.saveState().
String parser.parser.Regex.getCommandType (String s) throws CommandNameNotFoundException
For a string that's of generalType.Command, this will return the string class name of the command.
Definition at line 63 of file Regex.java.
References parser.parser.Regex.match().
Referenced by parser.parser.CommandFactory.createCommand().
static Regex parser.parser.Regex.getInstance () static
Definition at line 28 of file Regex.java.
References parser.parser.Regex.instance, and parser.parser.Regex.Regex().
Referenced by parser.parser.CommandFactory.createCommand(), model.VariableFactory.createVariable(), parser.parser.ToFactory.isolateToDeclaration(), parser.parser.Parser.parse(), model.VariablesCollection.saveState(), model.VariableString.setValue(), view.View.showAndChangeLanguage(), and view.View.tabChangeUpdate().
GeneralType parser.parser.Regex.getType (String s)
Returns the general type of a string, general type being eg. comment, command, variable, etc.
Definition at line 51 of file Regex.java.
References parser.parser.GeneralType.findType(), parser.parser.Regex.match(), and parser.parser.GeneralType.OTHER.
Referenced by model.VariableFactory.createVariable(), parser.parser.ToFactory.isolateToDeclaration(), parser.parser.Parser.parse(), and model.VariableString.setValue().
List<Entry<String, Pattern> > parser.parser.Regex.makePatterns (String syntax) private
Definition at line 86 of file Regex.java.
Referenced by parser.parser.Regex.changeLanguage(), and parser.parser.Regex.Regex().
boolean parser.parser.Regex.match (String input, Pattern regex) private
Definition at line 44 of file Regex.java.
Referenced by parser.parser.Regex.getCommandType(), and parser.parser.Regex.getType().
Member Data Documentation
List<Entry<String, Pattern> > parser.parser.Regex.commandPatterns = new ArrayList<>() package
Definition at line 18 of file Regex.java.
List<Entry<String, Pattern> > parser.parser.Regex.generalPatterns = new ArrayList<>() package
Definition at line 17 of file Regex.java.
Regex parser.parser.Regex.instance static private
Definition at line 20 of file Regex.java.
Referenced by parser.parser.Regex.getInstance().
String parser.parser.Regex.languageFileString package
Definition at line 16 of file Regex.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/parser/parser/Regex.java