slogo_team17: model.Model Class Reference
model.Model Class Reference
Public Member Functions
void parse (String command) throws CommandNameNotFoundException, SyntaxErrorWrongFormat, BadArgumentException
void setState (int workspaceID)
String saveLibrary (int workspaceID)
Static Public Member Functions
static Model getInstance ()
Private Member Functions
Model ()
Private Attributes
Parser myParser
List< State > myStates
State myActiveState
Static Private Attributes
static Model instance
Detailed Description
Definition at line 15 of file Model.java.
Constructor & Destructor Documentation
model.Model.Model () private
Definition at line 21 of file Model.java.
References model.Model.setState().
Referenced by model.Model.getInstance().
Member Function Documentation
static Model model.Model.getInstance () static
Definition at line 30 of file Model.java.
References model.Model.instance, and model.Model.Model().
Referenced by view.View.loadLibrary(), view.listwindows.CommandsListWindow.parseCommand(), view.components.CommandPort.runCommand(), view.View.saveCurrentLibrary(), and view.View.tabChangeUpdate().
void model.Model.parse (String command) throws CommandNameNotFoundException, SyntaxErrorWrongFormat, BadArgumentException
Definition at line 37 of file Model.java.
References model.CommandHistory.addCommand(), parser.nodes.CommandRoot.execute(), model.State.getCommandHistory(), and parser.parser.Parser.parse().
Referenced by view.View.loadLibrary(), view.listwindows.CommandsListWindow.parseCommand(), and view.components.CommandPort.runCommand().
String model.Model.saveLibrary (int workspaceID)
Concatenates a long string of UDCommands and variable declarations that already exist in the workspace, for the purpose of saving.
Definition at line 64 of file Model.java.
Referenced by view.View.saveCurrentLibrary().
void model.Model.setState (int workspaceID)
Switches to the workspace with the parameter ID. All parser calls will use the active state. If the call's ID is more than the current amount of states: if it is one more than the current amount, create a new state and add it to the list of states. else, rather than throw an error, set active state to 0th state.
Definition at line 49 of file Model.java.
References parser.parser.Parser.setActiveState().
Referenced by model.Model.Model(), and view.View.tabChangeUpdate().
Member Data Documentation
Model model.Model.instance static private
Definition at line 19 of file Model.java.
Referenced by model.Model.getInstance().
State model.Model.myActiveState private
Definition at line 18 of file Model.java.
Parser model.Model.myParser private
Definition at line 16 of file Model.java.
List<State> model.Model.myStates private
Definition at line 17 of file Model.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/Model.java