slogo_team17: view.components.WorkspaceFile Class Reference
view.components.WorkspaceFile Class Reference
Public Member Functions
WorkspaceFile ()
WorkspaceFile (Color c)
WorkspaceFile (Color c, int turtles)
WorkspaceFile (Color c, int turtles, String lang)
void setColor (Color c)
Color getColor ()
void setTitle (String title)
String getTitle ()
int getTurtles ()
void addTurtles ()
void setTurtles (int turtles)
Private Attributes
String myBgColor
Integer myTurtles
String myLanguage
String myTitle
Detailed Description
Definition at line 8 of file WorkspaceFile.java.
Constructor & Destructor Documentation
view.components.WorkspaceFile.WorkspaceFile ()
Definition at line 14 of file WorkspaceFile.java.
view.components.WorkspaceFile.WorkspaceFile (Color c)
Definition at line 21 of file WorkspaceFile.java.
view.components.WorkspaceFile.WorkspaceFile (Color c, int turtles)
Definition at line 27 of file WorkspaceFile.java.
view.components.WorkspaceFile.WorkspaceFile (Color c, int turtles, String lang)
Definition at line 33 of file WorkspaceFile.java.
Member Function Documentation
void view.components.WorkspaceFile.addTurtles ()
Definition at line 61 of file WorkspaceFile.java.
Color view.components.WorkspaceFile.getColor ()
Definition at line 44 of file WorkspaceFile.java.
Referenced by view.components.SLogoMenuBar.makePreferencesMenu().
String view.components.WorkspaceFile.getTitle ()
Definition at line 53 of file WorkspaceFile.java.
References view.components.WorkspaceFile.myTitle.
Referenced by view.components.SLogoMenuBar.makePreferencesMenu().
int view.components.WorkspaceFile.getTurtles ()
Definition at line 57 of file WorkspaceFile.java.
References view.components.WorkspaceFile.myTurtles.
void view.components.WorkspaceFile.setColor (Color c)
Definition at line 40 of file WorkspaceFile.java.
void view.components.WorkspaceFile.setTitle (String title)
Definition at line 49 of file WorkspaceFile.java.
Referenced by view.components.WorkspaceLoader.loadWorkspace().
void view.components.WorkspaceFile.setTurtles (int turtles)
Definition at line 65 of file WorkspaceFile.java.
Member Data Documentation
String view.components.WorkspaceFile.myBgColor private
Definition at line 9 of file WorkspaceFile.java.
String view.components.WorkspaceFile.myLanguage private
Definition at line 11 of file WorkspaceFile.java.
String view.components.WorkspaceFile.myTitle private
Definition at line 12 of file WorkspaceFile.java.
Referenced by view.components.WorkspaceFile.getTitle().
Integer view.components.WorkspaceFile.myTurtles private
Definition at line 10 of file WorkspaceFile.java.
Referenced by view.components.WorkspaceFile.getTurtles().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/components/WorkspaceFile.java