slogo_team17: view.turtle.TurtlePen Class Reference
view.turtle.TurtlePen Class Reference
Public Member Functions
TurtlePen (GraphicsContext graphicsContext)
void drawLine (Point2D start, Point2D end)
void setSolid ()
void setDashed ()
void setDotted ()
void setDashDot ()
void updatePen (Color color)
int getColorIndex ()
void setProperties (IntegerProperty colorIndex, DoubleProperty size)
Private Member Functions
void drawGappedLine (Point2D start, Point2D end)
Point2D[] generateDashVectorArray (Point2D directionVector)
Point2D getUnitVector (Point2D vector)
Private Attributes
GraphicsContext gc
IntegerProperty penColorIndex
DoubleProperty penSize
Integer initialColorIndex = 1
Double initialPenSize = 1.5
double[] dashLengthArray = SOLID
Static Private Attributes
static final double[] SOLID = {1, 0}
static final double[] DASHED = {7, 4}
static final double[] DOTTED = {1, 4}
static final double[] DASHDOT = {7, 3, 1, 3}
Detailed Description
Constructs lines according to set styles.
Author
lien
Definition at line 17 of file TurtlePen.java.
Constructor & Destructor Documentation
view.turtle.TurtlePen.TurtlePen (GraphicsContext graphicsContext)
Definition at line 34 of file TurtlePen.java.
Member Function Documentation
void view.turtle.TurtlePen.drawGappedLine (Point2D start, Point2D end) private
Definition at line 56 of file TurtlePen.java.
References view.turtle.TurtlePen.generateDashVectorArray().
Referenced by view.turtle.TurtlePen.drawLine().
void view.turtle.TurtlePen.drawLine (Point2D start, Point2D end)
Definition at line 40 of file TurtlePen.java.
References view.turtle.TurtlePen.drawGappedLine().
Referenced by view.turtle.TurtleImage.processUpdate().
Point2D [] view.turtle.TurtlePen.generateDashVectorArray (Point2D directionVector) private
Definition at line 90 of file TurtlePen.java.
References view.turtle.TurtlePen.getUnitVector().
Referenced by view.turtle.TurtlePen.drawGappedLine().
int view.turtle.TurtlePen.getColorIndex ()
Definition at line 134 of file TurtlePen.java.
Referenced by view.turtle.TurtleImage.processUpdate(), and view.turtle.TurtleImage.setPenProperties().
Point2D view.turtle.TurtlePen.getUnitVector (Point2D vector) private
Definition at line 105 of file TurtlePen.java.
Referenced by view.turtle.TurtlePen.generateDashVectorArray().
void view.turtle.TurtlePen.setDashDot ()
Definition at line 123 of file TurtlePen.java.
References view.turtle.TurtlePen.DASHDOT.
Referenced by view.turtle.TurtleImage.setLineStyleMenu().
void view.turtle.TurtlePen.setDashed ()
Definition at line 115 of file TurtlePen.java.
References view.turtle.TurtlePen.DASHED.
Referenced by view.turtle.TurtleImage.setLineStyleMenu().
void view.turtle.TurtlePen.setDotted ()
Definition at line 119 of file TurtlePen.java.
References view.turtle.TurtlePen.DOTTED.
Referenced by view.turtle.TurtleImage.setLineStyleMenu().
void view.turtle.TurtlePen.setProperties (IntegerProperty colorIndex, DoubleProperty size)
Definition at line 137 of file TurtlePen.java.
Referenced by view.turtle.TurtleImage.setPenProperties().
void view.turtle.TurtlePen.setSolid ()
Definition at line 111 of file TurtlePen.java.
References view.turtle.TurtlePen.SOLID.
Referenced by view.turtle.TurtleImage.setLineStyleMenu().
void view.turtle.TurtlePen.updatePen (Color color)
Definition at line 127 of file TurtlePen.java.
Referenced by view.turtle.TurtleImage.processUpdate(), and view.turtle.TurtleImage.setPenProperties().
Member Data Documentation
final double [] view.turtle.TurtlePen.DASHDOT = {7, 3, 1, 3} static private
Definition at line 29 of file TurtlePen.java.
Referenced by view.turtle.TurtlePen.setDashDot().
final double [] view.turtle.TurtlePen.DASHED = {7, 4} static private
Definition at line 27 of file TurtlePen.java.
Referenced by view.turtle.TurtlePen.setDashed().
double [] view.turtle.TurtlePen.dashLengthArray = SOLID private
Definition at line 32 of file TurtlePen.java.
final double [] view.turtle.TurtlePen.DOTTED = {1, 4} static private
Definition at line 28 of file TurtlePen.java.
Referenced by view.turtle.TurtlePen.setDotted().
GraphicsContext view.turtle.TurtlePen.gc private
Definition at line 18 of file TurtlePen.java.
Integer view.turtle.TurtlePen.initialColorIndex = 1 private
Definition at line 22 of file TurtlePen.java.
Double view.turtle.TurtlePen.initialPenSize = 1.5 private
Definition at line 23 of file TurtlePen.java.
IntegerProperty view.turtle.TurtlePen.penColorIndex private
Definition at line 20 of file TurtlePen.java.
DoubleProperty view.turtle.TurtlePen.penSize private
Definition at line 21 of file TurtlePen.java.
final double [] view.turtle.TurtlePen.SOLID = {1, 0} static private
Definition at line 26 of file TurtlePen.java.
Referenced by view.turtle.TurtlePen.setSolid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/turtle/TurtlePen.java