slogo_team17: view.listwindows.ListWindow Class Reference
view.listwindows.ListWindow Class Reference abstract
Public Member Functions
ListWindow (int w, int h, String label)
Protected Attributes
BorderPane myPane
Label myLabel
VBox myList
ScrollPane myScrollPane
int width
int height
Private Member Functions
void addLabel (String label)
void initScrollList ()
Detailed Description
Generic window to display boxes, with a scroll bar as needed.
Author
lien
Definition at line 16 of file ListWindow.java.
Constructor & Destructor Documentation
view.listwindows.ListWindow.ListWindow (int w, int h, String label)
Definition at line 25 of file ListWindow.java.
References view.listwindows.ListWindow.addLabel(), and view.listwindows.ListWindow.initScrollList().
Member Function Documentation
void view.listwindows.ListWindow.addLabel (String label) private
Definition at line 35 of file ListWindow.java.
Referenced by view.listwindows.ListWindow.ListWindow().
void view.listwindows.ListWindow.initScrollList () private
Definition at line 40 of file ListWindow.java.
Referenced by view.listwindows.ListWindow.ListWindow().
Member Data Documentation
int view.listwindows.ListWindow.height protected
Definition at line 23 of file ListWindow.java.
Label view.listwindows.ListWindow.myLabel protected
Definition at line 19 of file ListWindow.java.
VBox view.listwindows.ListWindow.myList protected
Definition at line 20 of file ListWindow.java.
Referenced by view.listwindows.VariablesWindow.update(), and view.listwindows.CommandsListWindow.update().
BorderPane view.listwindows.ListWindow.myPane protected
Definition at line 18 of file ListWindow.java.
ScrollPane view.listwindows.ListWindow.myScrollPane protected
Definition at line 21 of file ListWindow.java.
int view.listwindows.ListWindow.width protected
Definition at line 22 of file ListWindow.java.
Referenced by view.listwindows.CommandsListWindow.update().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/listwindows/ListWindow.java