slogo_team17: model.VariableInt Class Reference
model.VariableInt Class Reference
Public Member Functions
VariableInt (String name, int value)
Object getValue ()
Variable clone ()
void setValue (String edit) throws VariableWrongTypeException
Public Member Functions inherited from model.Variable
Variable (String name)
abstract Object getValue ()
abstract void setValue (String edit) throws VariableWrongTypeException
Private Attributes
IntegerProperty myProperty
Additional Inherited Members
Protected Member Functions inherited from model.Variable
StringProperty getStringProperty ()
StringProperty getNameProperty ()
Protected Attributes inherited from model.Variable
StringProperty myDisplayProperty
StringProperty myNameProperty
Detailed Description
Definition at line 10 of file VariableInt.java.
Constructor & Destructor Documentation
model.VariableInt.VariableInt (String name, int value)
Definition at line 13 of file VariableInt.java.
References model.Variable.myDisplayProperty.
Referenced by model.VariableInt.clone().
Member Function Documentation
Variable model.VariableInt.clone ()
Definition at line 26 of file VariableInt.java.
References model.Variable.getNameProperty(), model.VariableInt.getValue(), and model.VariableInt.VariableInt().
Object model.VariableInt.getValue ()
Definition at line 21 of file VariableInt.java.
Referenced by model.VariableInt.clone().
void model.VariableInt.setValue (String edit) throws VariableWrongTypeException
Definition at line 31 of file VariableInt.java.
Member Data Documentation
IntegerProperty model.VariableInt.myProperty private
Definition at line 11 of file VariableInt.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/VariableInt.java