slogo_team17: parser.parser.ToFactory Class Reference
parser.parser.ToFactory Class Reference
Public Member Functions
SyntaxNode createTo (String[] stream, State myState, Stack< SyntaxNode > input, int index) throws CommandNameNotFoundException
Static Public Member Functions
static ToFactory getInstance ()
Private Member Functions
ToFactory ()
String isolateToDeclaration (String[] commandStream, int toIndex)
Static Private Attributes
static ToFactory instance
Detailed Description
Definition at line 12 of file ToFactory.java.
Constructor & Destructor Documentation
parser.parser.ToFactory.ToFactory () private
Definition at line 15 of file ToFactory.java.
Referenced by parser.parser.ToFactory.getInstance().
Member Function Documentation
SyntaxNode parser.parser.ToFactory.createTo (String[] stream, State myState, Stack< SyntaxNode > input, int index) throws CommandNameNotFoundException
Definition at line 26 of file ToFactory.java.
References parser.parser.ToFactory.isolateToDeclaration().
static ToFactory parser.parser.ToFactory.getInstance () static
Definition at line 19 of file ToFactory.java.
References parser.parser.ToFactory.instance, and parser.parser.ToFactory.ToFactory().
Referenced by parser.parser.Parser.parse().
String parser.parser.ToFactory.isolateToDeclaration (String[] commandStream, int toIndex) private
Kind of a hacky solution to go through the command stream starting at a command "To" and recreating the "To name [ variables ] [ commands ]" string. Author: Kaighn
Definition at line 43 of file ToFactory.java.
References parser.parser.Regex.getInstance(), parser.parser.Regex.getType(), parser.parser.GeneralType.LISTEND, and parser.parser.GeneralType.LISTSTART.
Referenced by parser.parser.ToFactory.createTo().
Member Data Documentation
ToFactory parser.parser.ToFactory.instance static private
Definition at line 13 of file ToFactory.java.
Referenced by parser.parser.ToFactory.getInstance().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/parser/parser/ToFactory.java