slogo_team17: model.Coordinates Class Reference
model.Coordinates Class Reference
Public Member Functions
Coordinates (double x, double y)
Coordinates (Coordinates c)
void addCoordinates (Coordinates p)
void add (double x, double y)
void scale (double factor)
double getX ()
double getY ()
boolean equals (Coordinates c)
double distance (Coordinates c)
Private Attributes
Point2D myPoint
Detailed Description
Definition at line 5 of file Coordinates.java.
Constructor & Destructor Documentation
model.Coordinates.Coordinates (double x, double y)
Definition at line 8 of file Coordinates.java.
model.Coordinates.Coordinates (Coordinates c)
Definition at line 11 of file Coordinates.java.
References model.Coordinates.getX(), and model.Coordinates.getY().
Member Function Documentation
void model.Coordinates.add (double x, double y)
Definition at line 17 of file Coordinates.java.
void model.Coordinates.addCoordinates (Coordinates p)
Definition at line 14 of file Coordinates.java.
References model.Coordinates.getX(), and model.Coordinates.getY().
Referenced by model.TurtleSingle.moveDistance(), and model.TurtleSingle.moveToPosition().
double model.Coordinates.distance (Coordinates c)
Definition at line 33 of file Coordinates.java.
References model.Coordinates.getX(), and model.Coordinates.getY().
Referenced by model.TurtleSingle.moveToPosition().
boolean model.Coordinates.equals (Coordinates c)
Definition at line 29 of file Coordinates.java.
References model.Coordinates.getX(), and model.Coordinates.getY().
Referenced by parser.commands.ParserTest.testParse().
double model.Coordinates.getX ()
Definition at line 23 of file Coordinates.java.
Referenced by model.Coordinates.addCoordinates(), model.Coordinates.Coordinates(), model.Coordinates.distance(), model.Coordinates.equals(), model.TurtleSingle.moveToPosition(), and model.TurtleSingle.setTowards().
double model.Coordinates.getY ()
Definition at line 26 of file Coordinates.java.
Referenced by model.Coordinates.addCoordinates(), model.Coordinates.Coordinates(), model.Coordinates.distance(), model.Coordinates.equals(), model.TurtleSingle.moveToPosition(), view.turtle.TurtleImage.processUpdate(), and model.TurtleSingle.setTowards().
void model.Coordinates.scale (double factor)
Definition at line 20 of file Coordinates.java.
Referenced by model.TurtleSingle.distanceToCoordinates().
Member Data Documentation
Point2D model.Coordinates.myPoint private
Definition at line 6 of file Coordinates.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/Coordinates.java