slogo_team17: view.components.CommandPort Class Reference
view.components.CommandPort Class Reference
Public Member Functions
CommandPort (double width, double height)
Private Member Functions
void runCommand ()
void enterDebugMode ()
void runCommand (KeyEvent e)
void clearField (TextField tf)
Private Attributes
TextField myTextField
Button myRunButton
Button myDebugButton
Static Private Attributes
static final String COMMAND_PROMPT = "Enter your command here"
static final String RUN = "Run"
static final String DEBUG = "DEBUG"
Detailed Description
Definition at line 15 of file CommandPort.java.
Constructor & Destructor Documentation
view.components.CommandPort.CommandPort (double width, double height)
Definition at line 25 of file CommandPort.java.
References view.components.CommandPort.clearField(), view.components.CommandPort.enterDebugMode(), and view.components.CommandPort.runCommand().
Member Function Documentation
void view.components.CommandPort.clearField (TextField tf) private
Definition at line 62 of file CommandPort.java.
Referenced by view.components.CommandPort.CommandPort().
void view.components.CommandPort.enterDebugMode () private
Definition at line 53 of file CommandPort.java.
References view.View.addDebuger(), and view.View.getInstance().
Referenced by view.components.CommandPort.CommandPort().
void view.components.CommandPort.runCommand () private
Definition at line 41 of file CommandPort.java.
References model.Model.getInstance(), view.View.getInstance(), model.Model.parse(), and view.View.showDialog().
Referenced by view.components.CommandPort.CommandPort(), and view.components.CommandPort.runCommand().
void view.components.CommandPort.runCommand (KeyEvent e) private
Definition at line 56 of file CommandPort.java.
References view.components.CommandPort.runCommand().
Member Data Documentation
final String view.components.CommandPort.COMMAND_PROMPT = "Enter your command here" static private
Definition at line 17 of file CommandPort.java.
final String view.components.CommandPort.DEBUG = "DEBUG" static private
Definition at line 19 of file CommandPort.java.
Button view.components.CommandPort.myDebugButton private
Definition at line 23 of file CommandPort.java.
Button view.components.CommandPort.myRunButton private
Definition at line 22 of file CommandPort.java.
TextField view.components.CommandPort.myTextField private
Definition at line 21 of file CommandPort.java.
final String view.components.CommandPort.RUN = "Run" static private
Definition at line 18 of file CommandPort.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/view/components/CommandPort.java