slogo_team17: model.ViewUpdate Interface Reference
model.ViewUpdate Interface Reference
Public Member Functions
int getPaletteB ()
int getPaletteG ()
int getPaletteR ()
int getPaletteIndex ()
boolean isClear ()
boolean isClearStamps ()
Detailed Description
Simplifies the interface of a ViewOptions by only allowing these read methods.
Author
Owner
Definition at line 8 of file ViewUpdate.java.
Member Function Documentation
int model.ViewUpdate.getPaletteB ()
Implemented in model.ViewOptions.
Referenced by view.components.TurtleWindow.update().
int model.ViewUpdate.getPaletteG ()
Implemented in model.ViewOptions.
Referenced by view.components.TurtleWindow.update().
int model.ViewUpdate.getPaletteIndex ()
Implemented in model.ViewOptions.
Referenced by view.components.TurtleWindow.update().
int model.ViewUpdate.getPaletteR ()
Implemented in model.ViewOptions.
Referenced by view.components.TurtleWindow.update().
boolean model.ViewUpdate.isClear ()
Implemented in model.ViewOptions.
boolean model.ViewUpdate.isClearStamps ()
Implemented in model.ViewOptions.
Referenced by view.components.TurtleWindow.update().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/ViewUpdate.java