slogo_team17: model.VariableString Class Reference
model.VariableString Class Reference
Public Member Functions
VariableString (String name, String value)
Object getValue ()
Variable clone ()
void setValue (String edit) throws VariableWrongTypeException
Public Member Functions inherited from model.Variable
Variable (String name)
abstract Object getValue ()
abstract void setValue (String edit) throws VariableWrongTypeException
Private Attributes
StringProperty myProperty
Additional Inherited Members
Protected Member Functions inherited from model.Variable
StringProperty getStringProperty ()
StringProperty getNameProperty ()
Protected Attributes inherited from model.Variable
StringProperty myDisplayProperty
StringProperty myNameProperty
Detailed Description
Definition at line 11 of file VariableString.java.
Constructor & Destructor Documentation
model.VariableString.VariableString (String name, String value)
Definition at line 14 of file VariableString.java.
References model.Variable.myDisplayProperty.
Referenced by model.VariableString.clone().
Member Function Documentation
Variable model.VariableString.clone ()
Definition at line 27 of file VariableString.java.
References model.Variable.getNameProperty(), model.VariableString.getValue(), and model.VariableString.VariableString().
Object model.VariableString.getValue ()
Definition at line 22 of file VariableString.java.
Referenced by model.VariableString.clone().
void model.VariableString.setValue (String edit) throws VariableWrongTypeException
Definition at line 32 of file VariableString.java.
References parser.parser.GeneralType.CONSTANT, parser.parser.Regex.getInstance(), view.View.getInstance(), parser.parser.Regex.getType(), and view.View.showDialog().
Member Data Documentation
StringProperty model.VariableString.myProperty private
Definition at line 12 of file VariableString.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/slogo_team17/repository/src/model/VariableString.java